// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vverilator_top.h for the primary calling header

#ifndef VERILATED_VVERILATOR_TOP_VERILATOR_TOP_H_
#define VERILATED_VVERILATOR_TOP_VERILATOR_TOP_H_  // guard

#include "verilated.h"

class Vverilator_top__Syms;
class Vverilator_top_BoothInterBase;
class Vverilator_top_WallaceTreeBase;


class Vverilator_top_verilator_top final : public VerilatedModule {
  public:
    // CELLS
    Vverilator_top_BoothInterBase* __PVT__cpu__DOT__u_mul__DOT__fir;
    Vverilator_top_BoothInterBase* __PVT__cpu__DOT__u_mul__DOT__las;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__firs;
    Vverilator_top_BoothInterBase* __PVT__cpu__DOT__u_mul__DOT__boothfor__BRA__2__KET____DOT__ai;
    Vverilator_top_BoothInterBase* __PVT__cpu__DOT__u_mul__DOT__boothfor__BRA__4__KET____DOT__ai;
    Vverilator_top_BoothInterBase* __PVT__cpu__DOT__u_mul__DOT__boothfor__BRA__6__KET____DOT__ai;
    Vverilator_top_BoothInterBase* __PVT__cpu__DOT__u_mul__DOT__boothfor__BRA__8__KET____DOT__ai;
    Vverilator_top_BoothInterBase* __PVT__cpu__DOT__u_mul__DOT__boothfor__BRA__10__KET____DOT__ai;
    Vverilator_top_BoothInterBase* __PVT__cpu__DOT__u_mul__DOT__boothfor__BRA__12__KET____DOT__ai;
    Vverilator_top_BoothInterBase* __PVT__cpu__DOT__u_mul__DOT__boothfor__BRA__14__KET____DOT__ai;
    Vverilator_top_BoothInterBase* __PVT__cpu__DOT__u_mul__DOT__boothfor__BRA__16__KET____DOT__ai;
    Vverilator_top_BoothInterBase* __PVT__cpu__DOT__u_mul__DOT__boothfor__BRA__18__KET____DOT__ai;
    Vverilator_top_BoothInterBase* __PVT__cpu__DOT__u_mul__DOT__boothfor__BRA__20__KET____DOT__ai;
    Vverilator_top_BoothInterBase* __PVT__cpu__DOT__u_mul__DOT__boothfor__BRA__22__KET____DOT__ai;
    Vverilator_top_BoothInterBase* __PVT__cpu__DOT__u_mul__DOT__boothfor__BRA__24__KET____DOT__ai;
    Vverilator_top_BoothInterBase* __PVT__cpu__DOT__u_mul__DOT__boothfor__BRA__26__KET____DOT__ai;
    Vverilator_top_BoothInterBase* __PVT__cpu__DOT__u_mul__DOT__boothfor__BRA__28__KET____DOT__ai;
    Vverilator_top_BoothInterBase* __PVT__cpu__DOT__u_mul__DOT__boothfor__BRA__30__KET____DOT__ai;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__1__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__2__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__3__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__4__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__5__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__6__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__7__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__8__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__9__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__10__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__11__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__12__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__13__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__14__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__15__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__16__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__17__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__18__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__19__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__20__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__21__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__22__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__23__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__24__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__25__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__26__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__27__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__28__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__29__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__30__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__31__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__32__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__33__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__34__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__35__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__36__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__37__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__38__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__39__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__40__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__41__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__42__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__43__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__44__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__45__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__46__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__47__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__48__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__49__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__50__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__51__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__52__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__53__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__54__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__55__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__56__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__57__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__58__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__59__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__60__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__61__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__62__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase* __PVT__cpu__DOT__u_mul__DOT__wallacefor__BRA__63__KET____DOT__bi;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(rst,0,0);
        VL_IN8(clk,0,0);
        CData/*0:0*/ __PVT__cpu_inst_en;
        CData/*3:0*/ __PVT__cpu_inst_we;
        CData/*0:0*/ __PVT__cpu_data_en;
        CData/*3:0*/ __PVT__cpu_data_we;
        CData/*3:0*/ debug_wb_rf_we;
        CData/*4:0*/ debug_wb_rf_wnum;
        CData/*0:0*/ debug_wb_is_csr_wr_o;
        CData/*0:0*/ __PVT__data_sram_en;
        CData/*0:0*/ __PVT__data_sram_we;
        CData/*3:0*/ __PVT__wire_arid;
        CData/*7:0*/ __PVT__wire_arlen;
        CData/*2:0*/ __PVT__wire_arsize;
        CData/*0:0*/ __PVT__wire_arvalid;
        CData/*0:0*/ __PVT__wire_arready;
        CData/*3:0*/ __PVT__wire_rid;
        CData/*1:0*/ __PVT__wire_rresp;
        CData/*0:0*/ __PVT__wire_rlast;
        CData/*0:0*/ __PVT__wire_rvalid;
        CData/*0:0*/ __PVT__wire_rready;
        CData/*7:0*/ __PVT__wire_awlen;
        CData/*2:0*/ __PVT__wire_awsize;
        CData/*0:0*/ __PVT__wire_awvalid;
        CData/*0:0*/ __PVT__wire_awready;
        CData/*3:0*/ __PVT__wire_wstrb;
        CData/*0:0*/ __PVT__wire_wlast;
        CData/*0:0*/ __PVT__wire_wvalid;
        CData/*0:0*/ __PVT__wire_wready;
        CData/*1:0*/ __PVT__wire_bresp;
        CData/*0:0*/ __PVT__wire_bvalid;
        CData/*0:0*/ __PVT__wire_bready;
        CData/*3:0*/ __PVT__wire_bid;
        CData/*0:0*/ __PVT__cpu_inst_req;
        CData/*0:0*/ __PVT__cpu_inst_wr;
        CData/*1:0*/ __PVT__cpu_inst_size;
        CData/*3:0*/ __PVT__cpu_inst_wstrb;
        CData/*0:0*/ __PVT__cpu_inst_addr_ok;
        CData/*0:0*/ __PVT__cpu_inst_data_ok;
        CData/*0:0*/ __PVT__cpu_data_req;
        CData/*0:0*/ __PVT__cpu_data_wr;
        CData/*1:0*/ __PVT__cpu_data_size;
        CData/*3:0*/ __PVT__cpu_data_wstrb;
        CData/*0:0*/ __PVT__cpu_data_addr_ok;
        CData/*0:0*/ __PVT__cpu_data_data_ok;
        CData/*0:0*/ __PVT__cpu__DOT__reset;
        CData/*0:0*/ __PVT__cpu__DOT__ds_allowin;
        CData/*0:0*/ __PVT__cpu__DOT__es_allowin;
        CData/*0:0*/ __PVT__cpu__DOT__ms_allowin;
        CData/*0:0*/ __PVT__cpu__DOT__fs_to_ds_valid;
        CData/*0:0*/ __PVT__cpu__DOT__ds_to_es_valid;
        CData/*0:0*/ __PVT__cpu__DOT__es_to_ms_valid;
        CData/*0:0*/ __PVT__cpu__DOT__ms_to_ws_valid;
        CData/*5:0*/ __PVT__cpu__DOT__ws_csr_ecode;
        CData/*0:0*/ __PVT__cpu__DOT__ws_llbit;
        CData/*0:0*/ __PVT__cpu__DOT__has_int;
        CData/*0:0*/ __PVT__cpu__DOT__csr_wr_en;
        CData/*0:0*/ __PVT__cpu__DOT__excp_flush;
        CData/*0:0*/ __PVT__cpu__DOT__ertn_flush;
        CData/*0:0*/ __PVT__cpu__DOT__idle_flush;
        CData/*0:0*/ __PVT__cpu__DOT__es_div_enable;
        CData/*0:0*/ __PVT__cpu__DOT__tlbrd_en;
        CData/*0:0*/ __PVT__cpu__DOT__invtlb_en;
        CData/*0:0*/ __PVT__cpu__DOT__data_tlb_v;
    };
    struct {
        CData/*1:0*/ __PVT__cpu__DOT__data_tlb_plv;
        CData/*0:0*/ __PVT__cpu__DOT__tlbfill_en;
        CData/*0:0*/ __PVT__cpu__DOT__tlbwr_en;
        CData/*0:0*/ __PVT__cpu__DOT__excp_tlbrefill;
        CData/*0:0*/ __PVT__cpu__DOT__csr_pg;
        CData/*0:0*/ __PVT__cpu__DOT__csr_da;
        CData/*1:0*/ __PVT__cpu__DOT__csr_plv;
        CData/*0:0*/ __PVT__cpu__DOT__inst_addr_trans_en;
        CData/*0:0*/ __PVT__cpu__DOT__data_addr_trans_en;
        CData/*0:0*/ __PVT__cpu__DOT__cacop_op_mode_di;
        CData/*0:0*/ __PVT__cpu__DOT__icacop_op_en;
        CData/*0:0*/ __PVT__cpu__DOT__dcacop_op_en;
        CData/*0:0*/ __PVT__cpu__DOT__dcache_unbusy;
        CData/*0:0*/ __PVT__cpu__DOT__fetch_en;
        CData/*0:0*/ __PVT__cpu__DOT__btb_taken;
        CData/*0:0*/ __PVT__cpu__DOT__btb_en;
        CData/*4:0*/ __PVT__cpu__DOT__btb_index;
        CData/*0:0*/ __PVT__cpu__DOT__btb_add_entry;
        CData/*0:0*/ __PVT__cpu__DOT__btb_operate_en;
        CData/*0:0*/ __PVT__cpu__DOT__btb_pre_error;
        CData/*0:0*/ __PVT__cpu__DOT__btb_target_error;
        CData/*0:0*/ __PVT__cpu__DOT__btb_right_orien;
        CData/*0:0*/ __PVT__cpu__DOT__data_fetch;
        CData/*0:0*/ __PVT__cpu__DOT__inst_valid;
        CData/*0:0*/ __PVT__cpu__DOT__inst_addr_ok;
        CData/*0:0*/ __PVT__cpu__DOT__inst_data_ok;
        CData/*0:0*/ __PVT__cpu__DOT__inst_rd_req;
        CData/*0:0*/ __PVT__cpu__DOT__inst_ret_valid;
        CData/*0:0*/ __PVT__cpu__DOT__inst_ret_last;
        CData/*0:0*/ __PVT__cpu__DOT__inst_wr_req;
        CData/*2:0*/ __PVT__cpu__DOT__inst_wr_type;
        CData/*3:0*/ __PVT__cpu__DOT__inst_wr_wstrb;
        CData/*0:0*/ __PVT__cpu__DOT__inst_uncache_en;
        CData/*0:0*/ __PVT__cpu__DOT__inst_tlb_excp_cancel_req;
        CData/*0:0*/ __PVT__cpu__DOT__inst_dmw0_en;
        CData/*0:0*/ __PVT__cpu__DOT__inst_dmw1_en;
        CData/*0:0*/ __PVT__cpu__DOT__data_valid;
        CData/*0:0*/ __PVT__cpu__DOT__data_op;
        CData/*2:0*/ __PVT__cpu__DOT__data_size;
        CData/*3:0*/ __PVT__cpu__DOT__data_wstrb;
        CData/*0:0*/ __PVT__cpu__DOT__data_addr_ok;
        CData/*0:0*/ __PVT__cpu__DOT__data_rd_req;
        CData/*2:0*/ __PVT__cpu__DOT__data_rd_type;
        CData/*0:0*/ __PVT__cpu__DOT__data_ret_valid;
        CData/*0:0*/ __PVT__cpu__DOT__data_ret_last;
        CData/*0:0*/ __PVT__cpu__DOT__data_wr_req;
        CData/*2:0*/ __PVT__cpu__DOT__data_wr_type;
        CData/*0:0*/ __PVT__cpu__DOT__data_uncache_en;
        CData/*0:0*/ __PVT__cpu__DOT__data_dmw0_en;
        CData/*0:0*/ __PVT__cpu__DOT__data_dmw1_en;
        CData/*0:0*/ __PVT__cpu__DOT__data_tlb_excp_cancel_req;
        CData/*0:0*/ __PVT__cpu__DOT__sc_cancel_req;
        CData/*0:0*/ __PVT__cpu__DOT__preld_en;
        CData/*0:0*/ __PVT__cpu__DOT__commit_inst;
        CData/*0:0*/ __PVT__cpu__DOT__cmt_valid;
        CData/*0:0*/ __PVT__cpu__DOT__cmt_cnt_inst;
        CData/*7:0*/ __PVT__cpu__DOT__cmt_inst_ld_en;
        CData/*7:0*/ __PVT__cpu__DOT__cmt_inst_st_en;
        CData/*0:0*/ __PVT__cpu__DOT__cmt_csr_rstat_en;
        CData/*0:0*/ __PVT__cpu__DOT__cmt_wen;
        CData/*7:0*/ __PVT__cpu__DOT__cmt_wdest;
        CData/*0:0*/ __PVT__cpu__DOT__cmt_excp_flush;
        CData/*0:0*/ __PVT__cpu__DOT__cmt_ertn;
        CData/*5:0*/ __PVT__cpu__DOT__cmt_csr_ecode;
    };
    struct {
        CData/*0:0*/ __PVT__cpu__DOT__cmt_tlbfill_en;
        CData/*4:0*/ __PVT__cpu__DOT__cmt_rand_index;
        CData/*0:0*/ __PVT__cpu__DOT__trap;
        CData/*7:0*/ __PVT__cpu__DOT__trap_code;
        CData/*0:0*/ __PVT__cpu__DOT__if_stage__DOT__fs_valid;
        CData/*0:0*/ __PVT__cpu__DOT__if_stage__DOT__fs_ready_go;
        CData/*0:0*/ __PVT__cpu__DOT__if_stage__DOT__fs_allowin;
        CData/*0:0*/ __PVT__cpu__DOT__if_stage__DOT__to_fs_valid;
        CData/*0:0*/ __PVT__cpu__DOT__if_stage__DOT__pfs_ready_go;
        CData/*0:0*/ __PVT__cpu__DOT__if_stage__DOT__pfs_excp_adef;
        CData/*0:0*/ __PVT__cpu__DOT__if_stage__DOT__fs_excp_tlbr;
        CData/*0:0*/ __PVT__cpu__DOT__if_stage__DOT__fs_excp_pif;
        CData/*0:0*/ __PVT__cpu__DOT__if_stage__DOT__fs_excp_ppi;
        CData/*0:0*/ __PVT__cpu__DOT__if_stage__DOT__fs_excp;
        CData/*0:0*/ __PVT__cpu__DOT__if_stage__DOT__fs_excp_num;
        CData/*0:0*/ __PVT__cpu__DOT__if_stage__DOT__flush_sign;
        CData/*0:0*/ __PVT__cpu__DOT__if_stage__DOT__inst_buff_enable;
        CData/*0:0*/ __PVT__cpu__DOT__if_stage__DOT__flush_inst_delay;
        CData/*0:0*/ __PVT__cpu__DOT__if_stage__DOT__flush_inst_go_dirt;
        CData/*0:0*/ __PVT__cpu__DOT__if_stage__DOT__idle_lock;
        CData/*0:0*/ __PVT__cpu__DOT__if_stage__DOT__flush_inst_req_state;
        CData/*2:0*/ __PVT__cpu__DOT__if_stage__DOT__br_target_inst_req_state;
        CData/*0:0*/ __PVT__cpu__DOT__if_stage__DOT__btb_lock_en;
        CData/*0:0*/ cpu__DOT__if_stage__DOT____VdfgTmp_h52ebff71__0;
        CData/*0:0*/ cpu__DOT__if_stage__DOT____VdfgTmp_ha3d303c7__0;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__ds_valid;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__ds_ready_go;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__rf_we;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__btb_pre_error_flush;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__src2_is_4;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__csr_mask;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__mem_sign_exted;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__dst_is_rj;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__csr_we;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_add_w;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_sub_w;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_slt;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_sltu;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_nor;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_and;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_or;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_xor;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_lu12i_w;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_addi_w;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_slti;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_sltui;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_pcaddi;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_pcaddu12i;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_andi;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_ori;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_xori;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_mul_w;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_mulh_w;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_mulh_wu;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_div_w;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_mod_w;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_div_wu;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_mod_wu;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_slli_w;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_srli_w;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_srai_w;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_sll_w;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_srl_w;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_sra_w;
    };
    struct {
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_ll_w;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_sc_w;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_ld_b;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_ld_bu;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_ld_h;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_ld_hu;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_ld_w;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_st_b;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_st_h;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_st_w;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_syscall;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_break;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_csrrd;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_csrwr;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_ertn;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_rdcntvl_w;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_rdcntvh_w;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_idle;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_tlbsrch;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_tlbrd;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_tlbwr;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_tlbfill;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_invtlb;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_cacop;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_valid_cacop;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_preld;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_dbar;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_ibar;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_nop;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__need_ui5;
        CData/*4:0*/ __PVT__cpu__DOT__id_stage__DOT__rf_raddr2;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__pipeline_no_empty;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__rj_eq_rd;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__rj_lt_rd_sign;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__rj_lt_rd_unsign;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__ms_forward_enable;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__excp;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_valid;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__excp_ipe;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__fs_excp;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__branch_slot_cancel;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__br_jirl;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__br_need_reg_data;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__br_to_btb;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_need_rj;
        CData/*0:0*/ __PVT__cpu__DOT__id_stage__DOT__inst_need_rkd;
        CData/*0:0*/ cpu__DOT__id_stage__DOT____VdfgTmp_hfea85cf8__0;
        CData/*0:0*/ cpu__DOT__id_stage__DOT____VdfgTmp_hbba4846b__0;
        CData/*0:0*/ cpu__DOT__id_stage__DOT____VdfgTmp_h1c4a3e54__0;
        CData/*0:0*/ cpu__DOT__id_stage__DOT____VdfgTmp_h19962199__0;
        CData/*0:0*/ cpu__DOT__id_stage__DOT____VdfgTmp_h38353e9a__0;
        CData/*0:0*/ cpu__DOT__id_stage__DOT____VdfgTmp_h6983a416__0;
        CData/*0:0*/ cpu__DOT__id_stage__DOT____VdfgTmp_h1d0e0636__0;
        CData/*4:0*/ cpu__DOT__id_stage__DOT____VdfgTmp_h416d0694__0;
        CData/*0:0*/ cpu__DOT__id_stage__DOT____VdfgTmp_hb469ad25__0;
        CData/*0:0*/ cpu__DOT__id_stage__DOT____VdfgTmp_hbc7c3b7a__0;
        CData/*0:0*/ cpu__DOT__id_stage__DOT____VdfgTmp_haf287d09__0;
        CData/*0:0*/ cpu__DOT__id_stage__DOT____VdfgTmp_hac115781__0;
        CData/*0:0*/ cpu__DOT__id_stage__DOT____VdfgTmp_h0663ec88__0;
        CData/*0:0*/ __PVT__cpu__DOT__exe_stage__DOT__is_csr_wr_i_r;
        CData/*0:0*/ __PVT__cpu__DOT__exe_stage__DOT__es_valid;
        CData/*0:0*/ __PVT__cpu__DOT__exe_stage__DOT__es_ready_go;
        CData/*0:0*/ __PVT__cpu__DOT__exe_stage__DOT__excp;
        CData/*0:0*/ __PVT__cpu__DOT__exe_stage__DOT__forward_enable;
    };
    struct {
        CData/*0:0*/ __PVT__cpu__DOT__exe_stage__DOT__excp_ale;
        CData/*0:0*/ __PVT__cpu__DOT__exe_stage__DOT__es_flush_sign;
        CData/*0:0*/ __PVT__cpu__DOT__exe_stage__DOT__access_mem;
        CData/*0:0*/ __PVT__cpu__DOT__exe_stage__DOT__dcache_req_or_inst_en;
        CData/*0:0*/ __PVT__cpu__DOT__exe_stage__DOT__icacop_inst;
        CData/*0:0*/ __PVT__cpu__DOT__exe_stage__DOT__dcacop_inst;
        CData/*0:0*/ __PVT__cpu__DOT__exe_stage__DOT__preld_inst;
        CData/*0:0*/ __PVT__cpu__DOT__exe_stage__DOT__u_alu__DOT__adder_cin;
        CData/*7:0*/ __PVT__cpu__DOT__u_div__DOT__count;
        CData/*0:0*/ __PVT__cpu__DOT__u_div__DOT__div_signed_buffer;
        CData/*0:0*/ __PVT__cpu__DOT__u_div__DOT__x_31_buffer;
        CData/*0:0*/ __PVT__cpu__DOT__u_div__DOT__y_31_buffer;
        CData/*0:0*/ __PVT__cpu__DOT__u_div__DOT__real_div_signed;
        CData/*0:0*/ __PVT__cpu__DOT__u_div__DOT__real_x_31;
        CData/*0:0*/ __PVT__cpu__DOT__u_div__DOT__complete_delay;
        CData/*0:0*/ __PVT__cpu__DOT__u_div__DOT__real_complete;
        CData/*2:0*/ cpu__DOT__u_mul__DOT____Vcellinp__las__y;
        CData/*0:0*/ __PVT__cpu__DOT__mem_stage__DOT__is_csr_wr_i_r;
        CData/*0:0*/ __PVT__cpu__DOT__mem_stage__DOT__ms_valid;
        CData/*0:0*/ __PVT__cpu__DOT__mem_stage__DOT__ms_ready_go;
        CData/*0:0*/ __PVT__cpu__DOT__mem_stage__DOT__data_buff_enable;
        CData/*0:0*/ __PVT__cpu__DOT__mem_stage__DOT__access_mem;
        CData/*0:0*/ __PVT__cpu__DOT__mem_stage__DOT__excp;
        CData/*0:0*/ __PVT__cpu__DOT__mem_stage__DOT__excp_tlbr;
        CData/*0:0*/ __PVT__cpu__DOT__mem_stage__DOT__excp_pil;
        CData/*0:0*/ __PVT__cpu__DOT__mem_stage__DOT__excp_pis;
        CData/*0:0*/ __PVT__cpu__DOT__mem_stage__DOT__excp_pme;
        CData/*0:0*/ __PVT__cpu__DOT__mem_stage__DOT__excp_ppi;
        CData/*7:0*/ __PVT__cpu__DOT__mem_stage__DOT__mem_byteLoaded;
        CData/*7:0*/ __PVT__cpu__DOT__mem_stage__DOT__tmp_data_index;
        CData/*3:0*/ __PVT__cpu__DOT__mem_stage__DOT__tmp_data_offset;
        CData/*0:0*/ __PVT__cpu__DOT__wb_stage__DOT__is_csr_wr_i_r;
        CData/*0:0*/ __PVT__cpu__DOT__wb_stage__DOT__ws_valid;
        CData/*0:0*/ cpu__DOT__wb_stage__DOT____VdfgTmp_h71ee0a69__0;
        CData/*3:0*/ cpu__DOT__wb_stage__DOT____VdfgTmp_h292b3a37__0;
        CData/*0:0*/ __PVT__cpu__DOT__u_csr__DOT__crmd_wen;
        CData/*0:0*/ __PVT__cpu__DOT__u_csr__DOT__tlbehi_wen;
        CData/*0:0*/ __PVT__cpu__DOT__u_csr__DOT__tcfg_wen;
        CData/*0:0*/ __PVT__cpu__DOT__u_csr__DOT__DMW0_wen;
        CData/*0:0*/ __PVT__cpu__DOT__u_csr__DOT__DMW1_wen;
        CData/*0:0*/ __PVT__cpu__DOT__u_csr__DOT__timer_en;
        CData/*0:0*/ __PVT__cpu__DOT__u_csr__DOT__llbit;
        CData/*0:0*/ __PVT__cpu__DOT__u_csr__DOT__tlbrd_valid_wr_en;
        CData/*0:0*/ __PVT__cpu__DOT__u_csr__DOT__tlbrd_invalid_wr_en;
        CData/*0:0*/ __PVT__cpu__DOT__u_csr__DOT__no_forward;
        CData/*0:0*/ cpu__DOT__u_csr__DOT____VdfgTmp_hce7fc8e0__0;
        CData/*0:0*/ __PVT__cpu__DOT__axi_bridge__DOT__read_requst_state;
        CData/*0:0*/ __PVT__cpu__DOT__axi_bridge__DOT__read_respond_state;
        CData/*2:0*/ __PVT__cpu__DOT__axi_bridge__DOT__write_requst_state;
        CData/*0:0*/ __PVT__cpu__DOT__axi_bridge__DOT__rd_requst_can_receive;
        CData/*2:0*/ __PVT__cpu__DOT__axi_bridge__DOT__data_real_rd_size;
        CData/*2:0*/ __PVT__cpu__DOT__axi_bridge__DOT__inst_real_rd_size;
        CData/*2:0*/ __PVT__cpu__DOT__axi_bridge__DOT__write_buffer_num;
        CData/*0:0*/ __PVT__cpu__DOT__axi_bridge__DOT__write_buffer_last;
        CData/*0:0*/ __PVT__cpu__DOT__addr_trans__DOT__we;
        CData/*4:0*/ __PVT__cpu__DOT__addr_trans__DOT__w_index;
        CData/*0:0*/ __PVT__cpu__DOT__addr_trans__DOT__w_e;
        CData/*0:0*/ __PVT__cpu__DOT__addr_trans__DOT__r_g;
        CData/*0:0*/ __PVT__cpu__DOT__addr_trans__DOT__r_e;
        CData/*0:0*/ __PVT__cpu__DOT__addr_trans__DOT__pg_mode;
        CData/*0:0*/ __PVT__cpu__DOT__addr_trans__DOT__da_mode;
        CData/*0:0*/ __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__s0_fetch_r;
        CData/*0:0*/ __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__s0_odd_page_r;
        CData/*0:0*/ __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__s1_fetch_r;
    };
    struct {
        CData/*0:0*/ __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__s1_odd_page_r;
        CData/*4:0*/ cpu__DOT__addr_trans__DOT__tlb_entry__DOT____Vcellout__en_match0__out;
        CData/*4:0*/ cpu__DOT__addr_trans__DOT__tlb_entry__DOT____Vcellout__en_match1__out;
        CData/*0:0*/ cpu__DOT__addr_trans__DOT__tlb_entry__DOT____VdfgTmp_h5fe09d4e__0;
        CData/*0:0*/ cpu__DOT__addr_trans__DOT__tlb_entry__DOT____VdfgTmp_h9c4ee013__0;
        CData/*3:0*/ cpu__DOT__addr_trans__DOT__tlb_entry__DOT__en_match0__DOT__one__DOT____Vcellinp__one__in;
        CData/*3:0*/ cpu__DOT__addr_trans__DOT__tlb_entry__DOT__en_match1__DOT__one__DOT____Vcellinp__one__in;
        CData/*0:0*/ __PVT__cpu__DOT__icache__DOT__request_buffer_op;
        CData/*7:0*/ __PVT__cpu__DOT__icache__DOT__request_buffer_index;
        CData/*3:0*/ __PVT__cpu__DOT__icache__DOT__request_buffer_offset;
        CData/*3:0*/ __PVT__cpu__DOT__icache__DOT__request_buffer_wstrb;
        CData/*0:0*/ __PVT__cpu__DOT__icache__DOT__request_buffer_uncache_en;
        CData/*0:0*/ __PVT__cpu__DOT__icache__DOT__request_buffer_icacop;
        CData/*1:0*/ __PVT__cpu__DOT__icache__DOT__request_buffer_cacop_op_mode;
        CData/*1:0*/ __PVT__cpu__DOT__icache__DOT__miss_buffer_replace_way;
        CData/*1:0*/ __PVT__cpu__DOT__icache__DOT__miss_buffer_ret_num;
        CData/*1:0*/ __PVT__cpu__DOT__icache__DOT__ret_num_add_one;
        CData/*1:0*/ __PVT__cpu__DOT__icache__DOT__way_hit;
        CData/*0:0*/ __PVT__cpu__DOT__icache__DOT__cache_hit;
        CData/*1:0*/ __PVT__cpu__DOT__icache__DOT__way_wr_en;
        CData/*0:0*/ __PVT__cpu__DOT__icache__DOT__cacop_op_mode0;
        CData/*0:0*/ __PVT__cpu__DOT__icache__DOT__cacop_op_mode1;
        CData/*0:0*/ __PVT__cpu__DOT__icache__DOT__cacop_op_mode2;
        CData/*1:0*/ __PVT__cpu__DOT__icache__DOT__replace_way;
        CData/*1:0*/ __PVT__cpu__DOT__icache__DOT__invalid_way;
        CData/*0:0*/ __PVT__cpu__DOT__icache__DOT__cacop_op_mode2_hit_wr;
        CData/*1:0*/ __PVT__cpu__DOT__icache__DOT__lookup_way_hit_buffer;
        CData/*3:0*/ __PVT__cpu__DOT__icache__DOT__real_offset;
        CData/*7:0*/ __PVT__cpu__DOT__icache__DOT__real_index;
        CData/*0:0*/ __PVT__cpu__DOT__icache__DOT__req_or_inst_valid;
        CData/*4:0*/ __PVT__cpu__DOT__icache__DOT__main_state;
        CData/*0:0*/ __PVT__cpu__DOT__icache__DOT__rd_req_buffer;
        CData/*1:0*/ cpu__DOT__icache__DOT____Vcellinp__sel_one_invalid__in;
        CData/*0:0*/ cpu__DOT__icache__DOT____Vcellinp__tagv_ram_way__BRA__0__KET____DOT__u__wea;
        CData/*0:0*/ cpu__DOT__icache__DOT____Vcellinp__tagv_ram_way__BRA__0__KET____DOT__u__ena;
        CData/*7:0*/ cpu__DOT__icache__DOT____Vcellinp__tagv_ram_way__BRA__0__KET____DOT__u__addra;
        CData/*0:0*/ cpu__DOT__icache__DOT____Vcellinp__tagv_ram_way__BRA__1__KET____DOT__u__wea;
        CData/*0:0*/ cpu__DOT__icache__DOT____VdfgTmp_hf6d3044e__0;
        CData/*0:0*/ cpu__DOT__icache__DOT____VdfgTmp_he890b2ef__0;
        CData/*0:0*/ cpu__DOT__icache__DOT____VdfgTmp_h5d80e202__0;
        CData/*0:0*/ cpu__DOT__icache__DOT____VdfgTmp_h00af7739__0;
        CData/*7:0*/ __PVT__cpu__DOT__icache__DOT__lfsr__DOT__r_lfsr;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__request_uncache_en;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__request_buffer_op;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__request_buffer_preld;
        CData/*2:0*/ __PVT__cpu__DOT__dcache__DOT__request_buffer_size;
        CData/*7:0*/ __PVT__cpu__DOT__dcache__DOT__request_buffer_index;
        CData/*3:0*/ __PVT__cpu__DOT__dcache__DOT__request_buffer_offset;
        CData/*3:0*/ __PVT__cpu__DOT__dcache__DOT__request_buffer_wstrb;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__request_buffer_uncache_en;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__request_buffer_dcacop;
        CData/*1:0*/ __PVT__cpu__DOT__dcache__DOT__request_buffer_cacop_op_mode;
        CData/*1:0*/ __PVT__cpu__DOT__dcache__DOT__miss_buffer_replace_way;
        CData/*1:0*/ __PVT__cpu__DOT__dcache__DOT__miss_buffer_ret_num;
        CData/*1:0*/ __PVT__cpu__DOT__dcache__DOT__ret_num_add_one;
        CData/*7:0*/ __PVT__cpu__DOT__dcache__DOT__write_buffer_index;
        CData/*3:0*/ __PVT__cpu__DOT__dcache__DOT__write_buffer_wstrb;
        CData/*1:0*/ __PVT__cpu__DOT__dcache__DOT__write_buffer_way;
        CData/*3:0*/ __PVT__cpu__DOT__dcache__DOT__write_buffer_offset;
        CData/*1:0*/ __PVT__cpu__DOT__dcache__DOT__way_hit;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__cache_hit;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__replace_d;
        CData/*1:0*/ __PVT__cpu__DOT__dcache__DOT__replace_way;
        CData/*1:0*/ __PVT__cpu__DOT__dcache__DOT__invalid_way;
    };
    struct {
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__main_idle2lookup;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__main_lookup2lookup;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__uncache_wr;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__uncache_wr_buffer;
        CData/*1:0*/ __PVT__cpu__DOT__dcache__DOT__way_wr_en;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__cacop_op_mode0;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__cacop_op_mode1;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__cacop_op_mode2;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__cacop_op_mode2_hit_wr;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__cacop_op_mode2_hit_wr_buffer;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__preld_st_en;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__preld_ld_en;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__preld_ld_st_en;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__req_or_inst_valid;
        CData/*1:0*/ __PVT__cpu__DOT__dcache__DOT__lookup_way_hit_buffer;
        CData/*4:0*/ __PVT__cpu__DOT__dcache__DOT__main_state;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__write_buffer_state;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__rd_req_buffer;
        CData/*0:0*/ __PVT__cpu__DOT__dcache__DOT__cancel_req;
        CData/*0:0*/ cpu__DOT__dcache__DOT____Vcellinp__tagv_ram_way__BRA__0__KET____DOT__u__wea;
        CData/*0:0*/ cpu__DOT__dcache__DOT____Vcellinp__tagv_ram_way__BRA__0__KET____DOT__u__ena;
        CData/*7:0*/ cpu__DOT__dcache__DOT____Vcellinp__tagv_ram_way__BRA__0__KET____DOT__u__addra;
        CData/*0:0*/ cpu__DOT__dcache__DOT____Vcellinp__tagv_ram_way__BRA__1__KET____DOT__u__wea;
        CData/*0:0*/ cpu__DOT__dcache__DOT____VdfgTmp_h63343402__0;
        CData/*0:0*/ cpu__DOT__dcache__DOT____VdfgTmp_h9ac96f4b__0;
        CData/*1:0*/ cpu__DOT__dcache__DOT____VdfgTmp_h13703b6f__0;
        CData/*0:0*/ cpu__DOT__dcache__DOT____VdfgTmp_hdb34a219__0;
        CData/*0:0*/ cpu__DOT__dcache__DOT____VdfgTmp_hb6042862__0;
        CData/*0:0*/ cpu__DOT__dcache__DOT____VdfgTmp_h064d00c1__0;
        CData/*7:0*/ __PVT__cpu__DOT__dcache__DOT__lfsr__DOT__r_lfsr;
        CData/*0:0*/ __PVT__cpu__DOT__btb__DOT__fetch_en_r;
        CData/*3:0*/ __PVT__cpu__DOT__btb__DOT__ras_ptr;
        CData/*0:0*/ __PVT__cpu__DOT__btb__DOT__ras_full;
        CData/*0:0*/ __PVT__cpu__DOT__btb__DOT__ras_empty;
        CData/*0:0*/ __PVT__cpu__DOT__btb__DOT__ras_match;
        CData/*4:0*/ __PVT__cpu__DOT__btb__DOT__btb_match_index;
        CData/*4:0*/ __PVT__cpu__DOT__btb__DOT__btb_random_index;
        CData/*3:0*/ __PVT__cpu__DOT__btb__DOT__ras_random_index;
        CData/*4:0*/ __PVT__cpu__DOT__btb__DOT__btb_add_entry_index;
        CData/*4:0*/ __PVT__cpu__DOT__btb__DOT__btb_add_entry_index_r;
        CData/*3:0*/ __PVT__cpu__DOT__btb__DOT__ras_add_entry_index;
        CData/*0:0*/ __PVT__cpu__DOT__btb__DOT__btb_add_entry_r;
        CData/*5:0*/ __PVT__cpu__DOT__btb__DOT__fcsr;
        CData/*3:0*/ cpu__DOT__btb__DOT__sel_one_untaken_entry__DOT__coder__DOT__one__DOT____Vcellinp__one__in;
        CData/*3:0*/ cpu__DOT__btb__DOT__sel_one_untaken_entry__DOT__coder__DOT__two__DOT____Vcellinp__one__in;
        CData/*3:0*/ cpu__DOT__btb__DOT__sel_one_btb_entry__DOT__coder__DOT__one__DOT____Vcellinp__one__in;
        CData/*3:0*/ cpu__DOT__btb__DOT__sel_one_btb_entry__DOT__coder__DOT__two__DOT____Vcellinp__one__in;
        CData/*3:0*/ cpu__DOT__btb__DOT__encode_btb_match__DOT__one__DOT____Vcellinp__one__in;
        CData/*3:0*/ cpu__DOT__btb__DOT__encode_btb_match__DOT__two__DOT____Vcellinp__one__in;
        CData/*3:0*/ cpu__DOT__btb__DOT__encode_ras_match__DOT____Vcellinp__one__in;
        CData/*3:0*/ __PVT__axi_ram__DOT__state;
        CData/*3:0*/ __PVT__axi_ram__DOT__state1;
        CData/*0:0*/ __VdfgTmp_hb44e37ca__0;
        CData/*0:0*/ __VdfgTmp_h3a64b587__0;
        CData/*0:0*/ __VdfgTmp_h6802c383__0;
        CData/*0:0*/ __VdfgTmp_ha0f10682__0;
        CData/*0:0*/ __VdfgTmp_h3a96ee69__0;
        CData/*0:0*/ __VdfgTmp_h4dc072c1__0;
        CData/*0:0*/ __VdfgTmp_h2824a371__0;
        CData/*0:0*/ __VdfgTmp_h386fae7d__0;
        CData/*0:0*/ __VdfgTmp_hce0c4684__0;
        CData/*0:0*/ __VdfgTmp_ha7233986__0;
        CData/*0:0*/ __VdfgTmp_h2b5e8621__0;
        CData/*0:0*/ __VdfgTmp_h81e7e4c9__0;
    };
    struct {
        CData/*0:0*/ __VdfgTmp_hb231f61d__0;
        CData/*0:0*/ __VdfgTmp_hf2d875ee__0;
        CData/*0:0*/ __VdfgTmp_hf2232012__0;
        CData/*0:0*/ __VdfgTmp_he2772e6a__0;
        CData/*0:0*/ __VdfgTmp_h88048788__0;
        CData/*0:0*/ __VdfgTmp_h3f7dfeb7__0;
        CData/*0:0*/ __VdfgTmp_ha011a01e__0;
        CData/*0:0*/ __VdfgTmp_h6525c922__0;
        CData/*0:0*/ __VdfgTmp_h75708bee__0;
        CData/*0:0*/ __VdfgTmp_he92a5bc9__0;
        CData/*0:0*/ __VdfgTmp_h1e27bdaa__0;
        CData/*0:0*/ __VdfgTmp_hd67f03ee__0;
        CData/*0:0*/ __VdfgTmp_ha83e7e37__0;
        CData/*0:0*/ __VdfgTmp_h4b4d1d0f__0;
        CData/*0:0*/ __VdfgTmp_h08d4b213__0;
        CData/*0:0*/ __VdfgTmp_h65b1658b__0;
        CData/*0:0*/ __VdfgTmp_hbbbab294__0;
        CData/*0:0*/ __VdfgTmp_hc8484373__0;
        CData/*0:0*/ __VdfgTmp_h9f9dcade__0;
        CData/*0:0*/ __VdfgTmp_hac1c8e5b__0;
        CData/*0:0*/ __VdfgTmp_hb3c45e3f__0;
        CData/*0:0*/ __VdfgTmp_h28de6bba__0;
        CData/*0:0*/ __VdfgTmp_h281e3aa3__0;
        CData/*0:0*/ __VdfgTmp_h287d9e6a__0;
        CData/*0:0*/ __VdfgTmp_h29902bb6__0;
        CData/*0:0*/ __VdfgTmp_h282df2b4__0;
        CData/*0:0*/ __VdfgTmp_h28447f91__0;
        CData/*0:0*/ __VdfgTmp_h2f17bd15__0;
        CData/*0:0*/ __VdfgTmp_h2b34b778__0;
        CData/*0:0*/ __VdfgTmp_h2846d38b__0;
        CData/*0:0*/ __VdfgTmp_h283518d9__0;
        CData/*0:0*/ __VdfgTmp_h28d0af6a__0;
        CData/*0:0*/ __VdfgTmp_h28d16f34__0;
        CData/*0:0*/ __VdfgTmp_h28b5f3c3__0;
        CData/*0:0*/ __VdfgTmp_h28b1ebfc__0;
        CData/*0:0*/ __VdfgTmp_h2961036f__0;
        CData/*0:0*/ __VdfgTmp_hef3bf6e7__0;
        CData/*0:0*/ __VdfgTmp_hef3821b5__0;
        CData/*0:0*/ __VdfgTmp_hef7d2fec__0;
        CData/*0:0*/ __VdfgTmp_hd0f0d5da__0;
        CData/*0:0*/ __VdfgTmp_hd0f3f017__0;
        CData/*0:0*/ __VdfgTmp_hea1021fd__0;
        CData/*0:0*/ __VdfgTmp_hea79f5b1__0;
        CData/*0:0*/ __VdfgTmp_hef7d1ebb__0;
        CData/*0:0*/ __VdfgTmp_hef734879__0;
        CData/*0:0*/ __VdfgTmp_hec9625f7__0;
        CData/*0:0*/ __VdfgTmp_hef1da2f3__0;
        CData/*0:0*/ __VdfgTmp_h86498323__0;
        CData/*0:0*/ __VdfgTmp_h144a4430__0;
        CData/*0:0*/ __VdfgTmp_h1470b1c1__0;
        CData/*0:0*/ __VdfgTmp_h14758488__0;
        CData/*0:0*/ __VdfgTmp_h1449ec64__0;
        CData/*0:0*/ __VdfgTmp_h147b4aa2__0;
        CData/*0:0*/ __VdfgTmp_h295efed9__0;
        CData/*0:0*/ __VdfgTmp_h1492eda8__0;
        CData/*0:0*/ __VdfgTmp_h1478ca08__0;
        CData/*0:0*/ __VdfgTmp_h147c90ec__0;
        CData/*0:0*/ __VdfgTmp_h14673d06__0;
        CData/*0:0*/ __VdfgTmp_h1462d6b9__0;
        CData/*0:0*/ __VdfgTmp_h146f23bf__0;
        CData/*0:0*/ __VdfgTmp_h145a0ce5__0;
        CData/*0:0*/ __VdfgTmp_h14462e1a__0;
        CData/*0:0*/ __VdfgTmp_h1485ccbd__0;
        CData/*0:0*/ __VdfgTmp_h14afccdb__0;
    };
    struct {
        CData/*0:0*/ __VdfgTmp_h1468056a__0;
        CData/*0:0*/ __VdfgTmp_h14940457__0;
        CData/*0:0*/ __VdfgTmp_h1490813d__0;
        CData/*0:0*/ __VdfgTmp_h147e8bf1__0;
        CData/*0:0*/ __VdfgTmp_h147a4322__0;
        CData/*0:0*/ __VdfgTmp_h1427ccc7__0;
        CData/*0:0*/ __VdfgTmp_h14219459__0;
        CData/*0:0*/ __VdfgTmp_h144d61b4__0;
        CData/*0:0*/ __VdfgTmp_h14924f66__0;
        CData/*0:0*/ __VdfgTmp_h149ff3f7__0;
        CData/*0:0*/ __VdfgTmp_h149b35b7__0;
        CData/*0:0*/ __VdfgTmp_h145f01b1__0;
        CData/*0:0*/ __VdfgTmp_h145b0fca__0;
        CData/*0:0*/ __VdfgTmp_h88130675__0;
        CData/*0:0*/ __VdfgTmp_h287669a1__0;
        CData/*0:0*/ __VdfgTmp_h284b4e24__0;
        CData/*0:0*/ __VdfgTmp_h2b2d3ac1__0;
        CData/*0:0*/ __VdfgTmp_h2b22ba23__0;
        CData/*0:0*/ __VdfgTmp_h2b26b937__0;
        CData/*0:0*/ __VdfgTmp_h2b39d584__0;
        CData/*0:0*/ __VdfgTmp_h2b9f81d9__0;
        CData/*0:0*/ __VdfgTmp_h2b92025f__0;
        CData/*0:0*/ __VdfgTmp_h2b9503ed__0;
        CData/*0:0*/ __VdfgTmp_h2b227c39__0;
        CData/*0:0*/ __VdfgTmp_h2b2ff7d2__0;
        CData/*0:0*/ __VdfgTmp_h284bb0ae__0;
        CData/*0:0*/ __VdfgTmp_h2870c5f6__0;
        CData/*0:0*/ __VdfgTmp_h2872c95d__0;
        CData/*0:0*/ __VdfgTmp_h2bbd3cde__0;
        CData/*0:0*/ __VdfgTmp_h2b8ddfe0__0;
        CData/*0:0*/ __VdfgTmp_h286f7fb9__0;
        CData/*0:0*/ __VdfgTmp_h2bd4a660__0;
        CData/*0:0*/ __VdfgTmp_h2bd0af7c__0;
        CData/*0:0*/ __VdfgTmp_h2bd66e9a__0;
        CData/*0:0*/ __VdfgTmp_h2bd25251__0;
        CData/*0:0*/ __VdfgTmp_h2b9f70b0__0;
        CData/*0:0*/ __VdfgTmp_h28475190__0;
        CData/*0:0*/ __VdfgTmp_h28431d65__0;
        CData/*0:0*/ __VdfgTmp_h28610961__0;
        CData/*0:0*/ __VdfgTmp_h286d4908__0;
        CData/*0:0*/ __VdfgTmp_h2b8acf86__0;
        CData/*0:0*/ __VdfgTmp_h2b9506da__0;
        CData/*0:0*/ __VdfgTmp_h2b9112e1__0;
        CData/*0:0*/ __VdfgTmp_h21b09c90__0;
        CData/*0:0*/ __VdfgTmp_hd654fdc0__0;
        CData/*0:0*/ __VdfgTmp_hd64bffee__0;
        CData/*0:0*/ __VdfgTmp_hd64efe69__0;
        CData/*0:0*/ __VdfgTmp_hd72442ad__0;
        CData/*0:0*/ __VdfgTmp_hd71b4a8a__0;
        CData/*0:0*/ __VdfgTmp_hd65c44e5__0;
        CData/*0:0*/ __VdfgTmp_hd67691e4__0;
        CData/*0:0*/ __VdfgTmp_hd66a0d7d__0;
        CData/*0:0*/ __VdfgTmp_hd66f5582__0;
        CData/*0:0*/ __VdfgTmp_hd666047e__0;
        CData/*0:0*/ __VdfgTmp_hd638d239__0;
        CData/*0:0*/ __VdfgTmp_ha60326f2__0;
        CData/*0:0*/ __VdfgTmp_h2991042b__0;
        CData/*0:0*/ __VdfgTmp_h28667139__0;
        CData/*0:0*/ __VdfgTmp_h29e8ee51__0;
        CData/*0:0*/ __VdfgTmp_h29c04841__0;
        CData/*0:0*/ __VdfgTmp_h29f565de__0;
        CData/*0:0*/ __VdfgTmp_h29ed2521__0;
        CData/*0:0*/ __VdfgTmp_h284c4815__0;
        CData/*0:0*/ __VdfgTmp_h2b42431a__0;
    };
    struct {
        CData/*0:0*/ __VdfgTmp_h28a85f11__0;
        CData/*0:0*/ __VdfgTmp_h28689c53__0;
        CData/*0:0*/ __VdfgTmp_h2678667e__0;
        CData/*0:0*/ __VdfgTmp_h263ed55f__0;
        CData/*0:0*/ __VdfgTmp_h2865ac30__0;
        CData/*0:0*/ __VdfgTmp_h29829d30__0;
        CData/*0:0*/ __VdfgTmp_h2916341e__0;
        CData/*0:0*/ __VdfgTmp_h8651482e__0;
        CData/*0:0*/ __VdfgTmp_h86e948c6__0;
        CData/*0:0*/ __VdfgTmp_hd0d3d28e__0;
        CData/*0:0*/ __Vdly__cpu__DOT__u_csr__DOT__timer_en;
        CData/*0:0*/ __Vdly__cpu__DOT__axi_bridge__DOT__read_requst_state;
        CData/*2:0*/ __Vdly__cpu__DOT__axi_bridge__DOT__write_requst_state;
        CData/*0:0*/ __Vdly__wire_wlast;
        CData/*0:0*/ __Vdly__wire_bready;
        CData/*2:0*/ __Vdly__cpu__DOT__axi_bridge__DOT__write_buffer_num;
        CData/*3:0*/ __Vdlyvdim0__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_vppn__v0;
        CData/*0:0*/ __Vdlyvset__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_vppn__v0;
        CData/*3:0*/ __Vdlyvdim0__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_asid__v0;
        CData/*0:0*/ __Vdlyvset__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_asid__v0;
        CData/*4:0*/ __Vdly__cpu__DOT__icache__DOT__main_state;
        CData/*0:0*/ __Vdly__cpu__DOT__icache__DOT__request_buffer_icacop;
        CData/*4:0*/ __Vdly__cpu__DOT__dcache__DOT__main_state;
        CData/*0:0*/ __Vdly__cpu__DOT__dcache__DOT__write_buffer_state;
        CData/*7:0*/ __Vdlyvdim0__cpu__DOT__dcache__DOT__tagv_ram_way__BRA__0__KET____DOT__u__DOT__mem_reg__v0;
        CData/*0:0*/ __Vdlyvset__cpu__DOT__dcache__DOT__tagv_ram_way__BRA__0__KET____DOT__u__DOT__mem_reg__v0;
        CData/*7:0*/ __Vdlyvdim0__cpu__DOT__dcache__DOT__tagv_ram_way__BRA__1__KET____DOT__u__DOT__mem_reg__v0;
        CData/*0:0*/ __Vdlyvset__cpu__DOT__dcache__DOT__tagv_ram_way__BRA__1__KET____DOT__u__DOT__mem_reg__v0;
        CData/*0:0*/ __Vdly__wire_arready;
        CData/*0:0*/ __Vdly__wire_awready;
        CData/*0:0*/ __Vdly__wire_wready;
        CData/*0:0*/ __Vdly__wire_bvalid;
        SData/*15:0*/ __PVT__cpu__DOT__id_stage__DOT__op_25_22_d;
        SData/*15:0*/ __PVT__cpu__DOT__mem_stage__DOT__mem_halfLoaded;
        SData/*9:0*/ __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__s0_asid_r;
        SData/*9:0*/ __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__s1_asid_r;
        SData/*15:0*/ __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__match0;
        SData/*15:0*/ __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__match1;
        SData/*15:0*/ __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__s0_odd_page_buffer;
        SData/*15:0*/ __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__s1_odd_page_buffer;
        SData/*15:0*/ __PVT__cpu__DOT__btb__DOT__ras_valid;
        SData/*15:0*/ cpu__DOT__btb__DOT__encode_btb_match__DOT____Vcellinp__one__in;
        SData/*9:0*/ __Vdlyvval__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_asid__v0;
        IData/*31:0*/ __PVT__cpu_inst_addr;
        IData/*31:0*/ __PVT__cpu_inst_wdata;
        IData/*31:0*/ __PVT__cpu_inst_rdata;
        IData/*31:0*/ __PVT__cpu_data_addr;
        IData/*31:0*/ __PVT__cpu_data_wdata;
        IData/*31:0*/ __PVT__cpu_data_rdata;
        IData/*31:0*/ debug_wb_pc;
        IData/*31:0*/ debug_wb_rf_wdata;
        IData/*31:0*/ debug_wb_inst;
        IData/*31:0*/ csr_crmd_diff;
        IData/*31:0*/ csr_prmd_diff;
        IData/*31:0*/ csr_ectl_diff;
        IData/*31:0*/ csr_estat_diff;
        IData/*31:0*/ csr_era_diff;
        IData/*31:0*/ csr_badv_diff;
        IData/*31:0*/ csr_eentry_diff;
        IData/*31:0*/ csr_tlbidx_diff;
        IData/*31:0*/ csr_tlbehi_diff;
        IData/*31:0*/ csr_tlbelo0_diff;
        IData/*31:0*/ csr_tlbelo1_diff;
        IData/*31:0*/ csr_asid_diff;
    };
    struct {
        IData/*31:0*/ csr_save0_diff;
        IData/*31:0*/ csr_save1_diff;
        IData/*31:0*/ csr_save2_diff;
        IData/*31:0*/ csr_save3_diff;
        IData/*31:0*/ csr_tid_diff;
        IData/*31:0*/ csr_tcfg_diff;
        IData/*31:0*/ csr_tval_diff;
        IData/*31:0*/ csr_ticlr_diff;
        IData/*31:0*/ csr_llbctl_diff;
        IData/*31:0*/ csr_tlbrentry_diff;
        IData/*31:0*/ csr_dmw0_diff;
        IData/*31:0*/ csr_dmw1_diff;
        IData/*31:0*/ csr_pgdl_diff;
        IData/*31:0*/ csr_pgdh_diff;
        IData/*31:0*/ __PVT__data_sram_addr;
        IData/*31:0*/ __PVT__data_sram_wdata;
        IData/*31:0*/ __PVT__data_sram_rdata;
        IData/*31:0*/ __PVT__wire_araddr;
        IData/*31:0*/ __PVT__wire_rdata;
        IData/*31:0*/ __PVT__wire_awaddr;
        IData/*31:0*/ __PVT__wire_wdata;
        IData/*31:0*/ __PVT__cpu__DOT__rd_csr_data;
        IData/*31:0*/ __PVT__cpu__DOT__tlbr_tlbelo0;
        IData/*31:0*/ __PVT__cpu__DOT__tlbr_tlbelo1;
        IData/*31:0*/ __PVT__cpu__DOT__tlbr_tlbidx;
        IData/*31:0*/ __PVT__cpu__DOT__csr_dmw0;
        IData/*31:0*/ __PVT__cpu__DOT__csr_dmw1;
        IData/*31:0*/ __PVT__cpu__DOT__fetch_pc;
        IData/*31:0*/ __PVT__cpu__DOT__btb_ret_pc;
        IData/*31:0*/ __PVT__cpu__DOT__btb_right_target;
        VlWide<11>/*349:0*/ __PVT__cpu__DOT__ds_to_es_bus;
        VlWide<14>/*424:0*/ __PVT__cpu__DOT__es_to_ms_bus;
        IData/*31:0*/ __PVT__cpu__DOT__inst_rdata;
        IData/*31:0*/ __PVT__cpu__DOT__inst_rd_addr;
        IData/*31:0*/ __PVT__cpu__DOT__inst_wr_addr;
        VlWide<4>/*127:0*/ __PVT__cpu__DOT__inst_wr_data;
        IData/*31:0*/ __PVT__cpu__DOT__data_vaddr;
        IData/*19:0*/ __PVT__cpu__DOT__data_tag;
        IData/*31:0*/ __PVT__cpu__DOT__data_wdata;
        IData/*31:0*/ __PVT__cpu__DOT__data_rd_addr;
        VlWide<4>/*127:0*/ __PVT__cpu__DOT__data_wr_data;
        IData/*31:0*/ __PVT__cpu__DOT__cmt_ld_paddr;
        IData/*31:0*/ __PVT__cpu__DOT__cmt_ld_vaddr;
        IData/*31:0*/ __PVT__cpu__DOT__cmt_st_paddr;
        IData/*31:0*/ __PVT__cpu__DOT__cmt_st_vaddr;
        IData/*31:0*/ __PVT__cpu__DOT__cmt_st_data;
        IData/*31:0*/ __PVT__cpu__DOT__cmt_csr_data;
        IData/*31:0*/ __PVT__cpu__DOT__cmt_wdata;
        IData/*31:0*/ __PVT__cpu__DOT__cmt_pc;
        IData/*31:0*/ __PVT__cpu__DOT__cmt_inst;
        IData/*31:0*/ __PVT__cpu__DOT__if_stage__DOT__inst_rd_buff;
        IData/*31:0*/ __PVT__cpu__DOT__if_stage__DOT__btb_ret_pc_t;
        IData/*31:0*/ __PVT__cpu__DOT__if_stage__DOT__fs_pc;
        IData/*31:0*/ __PVT__cpu__DOT__if_stage__DOT__flush_inst_req_buffer;
        IData/*31:0*/ __PVT__cpu__DOT__if_stage__DOT__br_target_inst_req_buffer;
        VlWide<4>/*108:0*/ __PVT__cpu__DOT__id_stage__DOT__fs_to_ds_bus_r;
        IData/*31:0*/ __PVT__cpu__DOT__id_stage__DOT__btb_pre_error_flush_target;
        IData/*31:0*/ __PVT__cpu__DOT__id_stage__DOT__ds_imm;
        IData/*31:0*/ __PVT__cpu__DOT__id_stage__DOT__op_19_15_d;
        IData/*31:0*/ __PVT__cpu__DOT__id_stage__DOT__rd_d;
        IData/*31:0*/ __PVT__cpu__DOT__id_stage__DOT__rj_d;
        IData/*31:0*/ __PVT__cpu__DOT__id_stage__DOT__rk_d;
        IData/*31:0*/ __PVT__cpu__DOT__id_stage__DOT__rf_rdata1;
        IData/*31:0*/ __PVT__cpu__DOT__id_stage__DOT__rf_rdata2;
    };
    struct {
        IData/*31:0*/ __PVT__cpu__DOT__id_stage__DOT__ms_forward_data;
        VlWide<3>/*64:0*/ cpu__DOT__id_stage__DOT____VdfgTmp_h51300fe8__0;
        VlWide<3>/*64:0*/ cpu__DOT__id_stage__DOT____VdfgTmp_hef9191ce__0;
        VlWide<3>/*64:0*/ cpu__DOT__id_stage__DOT____VdfgTmp_ha01d14c2__0;
        IData/*31:0*/ __PVT__cpu__DOT__exe_stage__DOT__error_va;
        VlWide<11>/*349:0*/ __PVT__cpu__DOT__exe_stage__DOT__ds_to_es_bus_r;
        IData/*31:0*/ __PVT__cpu__DOT__exe_stage__DOT__exe_result;
        IData/*31:0*/ __PVT__cpu__DOT__exe_stage__DOT__u_alu__DOT__add_sub_result;
        IData/*31:0*/ __PVT__cpu__DOT__exe_stage__DOT__u_alu__DOT__or_result;
        IData/*31:0*/ __PVT__cpu__DOT__exe_stage__DOT__u_alu__DOT__lui_result;
        IData/*31:0*/ __PVT__cpu__DOT__exe_stage__DOT__u_alu__DOT__adder_a;
        IData/*31:0*/ __PVT__cpu__DOT__exe_stage__DOT__u_alu__DOT__adder_b;
        IData/*16:0*/ __PVT__cpu__DOT__u_mul__DOT__SecStageCarry;
        IData/*31:0*/ __PVT__cpu__DOT__u_mul__DOT__p;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__firs__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__1__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__2__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__3__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__4__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__5__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__6__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__7__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__8__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__9__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__10__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__11__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__12__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__13__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__14__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__15__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__16__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__17__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__18__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__19__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__20__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__21__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__22__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__23__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__24__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__25__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__26__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__27__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__28__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__29__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__30__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__31__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__32__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__33__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__34__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__35__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__36__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__37__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__38__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__39__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__40__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__41__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__42__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__43__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__44__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__45__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__46__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__47__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__48__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__49__KET____DOT__bi__InData;
    };
    struct {
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__50__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__51__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__52__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__53__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__54__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__55__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__56__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__57__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__58__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__59__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__60__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__61__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__62__KET____DOT__bi__InData;
        IData/*16:0*/ cpu__DOT__u_mul__DOT____Vcellinp__wallacefor__BRA__63__KET____DOT__bi__InData;
        VlWide<14>/*424:0*/ __PVT__cpu__DOT__mem_stage__DOT__es_to_ms_bus_r;
        IData/*31:0*/ __PVT__cpu__DOT__mem_stage__DOT__ms_rdata;
        IData/*31:0*/ __PVT__cpu__DOT__mem_stage__DOT__data_rd_buff;
        VlWide<16>/*492:0*/ __PVT__cpu__DOT__wb_stage__DOT__ms_to_ws_bus_r;
        VlWide<3>/*68:0*/ cpu__DOT__wb_stage__DOT____VdfgTmp_hdefe0a78__0;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_crmd;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_prmd;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_ectl;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_estat;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_era;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_badv;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_eentry;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_tlbidx;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_tlbehi;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_tlbelo0;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_tlbelo1;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_asid;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_cpuid;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_save0;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_save1;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_save2;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_save3;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_tid;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_tcfg;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_tval;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_cntc;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_ticlr;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_llbctl;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_tlbrentry;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_dmw0;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_dmw1;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_pgdl;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_pgdh;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_brk;
        IData/*31:0*/ __PVT__cpu__DOT__u_csr__DOT__csr_disable_cache;
        IData/*27:0*/ __PVT__cpu__DOT__u_csr__DOT__lladdr;
        VlWide<4>/*127:0*/ __PVT__cpu__DOT__axi_bridge__DOT__write_buffer_data;
        IData/*19:0*/ __PVT__cpu__DOT__addr_trans__DOT__s0_ppn;
        IData/*19:0*/ __PVT__cpu__DOT__addr_trans__DOT__s1_ppn;
        IData/*31:0*/ __PVT__cpu__DOT__addr_trans__DOT__inst_vaddr_buffer;
        IData/*31:0*/ __PVT__cpu__DOT__addr_trans__DOT__data_vaddr_buffer;
        IData/*31:0*/ __PVT__cpu__DOT__addr_trans__DOT__inst_paddr;
        IData/*31:0*/ __PVT__cpu__DOT__addr_trans__DOT__data_paddr;
        IData/*18:0*/ __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__s0_vppn_r;
        IData/*18:0*/ __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__s1_vppn_r;
        IData/*19:0*/ __PVT__cpu__DOT__icache__DOT__request_buffer_tag;
        IData/*31:0*/ __PVT__cpu__DOT__icache__DOT__request_buffer_wdata;
        IData/*19:0*/ __PVT__cpu__DOT__icache__DOT__real_tag;
        IData/*20:0*/ cpu__DOT__icache__DOT____Vcellinp__tagv_ram_way__BRA__0__KET____DOT__u__dina;
        IData/*31:0*/ __PVT__cpu__DOT__icache__DOT__data_ram_way__BRA__0__KET____DOT__data_ram_bank__BRA__0__KET____DOT__u__DOT__output_buffer;
    };
    struct {
        IData/*31:0*/ __PVT__cpu__DOT__icache__DOT__data_ram_way__BRA__0__KET____DOT__data_ram_bank__BRA__1__KET____DOT__u__DOT__output_buffer;
        IData/*31:0*/ __PVT__cpu__DOT__icache__DOT__data_ram_way__BRA__0__KET____DOT__data_ram_bank__BRA__2__KET____DOT__u__DOT__output_buffer;
        IData/*31:0*/ __PVT__cpu__DOT__icache__DOT__data_ram_way__BRA__0__KET____DOT__data_ram_bank__BRA__3__KET____DOT__u__DOT__output_buffer;
        IData/*31:0*/ __PVT__cpu__DOT__icache__DOT__data_ram_way__BRA__1__KET____DOT__data_ram_bank__BRA__0__KET____DOT__u__DOT__output_buffer;
        IData/*31:0*/ __PVT__cpu__DOT__icache__DOT__data_ram_way__BRA__1__KET____DOT__data_ram_bank__BRA__1__KET____DOT__u__DOT__output_buffer;
        IData/*31:0*/ __PVT__cpu__DOT__icache__DOT__data_ram_way__BRA__1__KET____DOT__data_ram_bank__BRA__2__KET____DOT__u__DOT__output_buffer;
        IData/*31:0*/ __PVT__cpu__DOT__icache__DOT__data_ram_way__BRA__1__KET____DOT__data_ram_bank__BRA__3__KET____DOT__u__DOT__output_buffer;
        IData/*20:0*/ __PVT__cpu__DOT__icache__DOT__tagv_ram_way__BRA__0__KET____DOT__u__DOT__output_buffer;
        IData/*20:0*/ __PVT__cpu__DOT__icache__DOT__tagv_ram_way__BRA__1__KET____DOT__u__DOT__output_buffer;
        IData/*19:0*/ __PVT__cpu__DOT__dcache__DOT__request_buffer_tag;
        IData/*31:0*/ __PVT__cpu__DOT__dcache__DOT__request_buffer_wdata;
        IData/*31:0*/ __PVT__cpu__DOT__dcache__DOT__write_buffer_wdata;
        IData/*31:0*/ __PVT__cpu__DOT__dcache__DOT__refill_data;
        IData/*20:0*/ cpu__DOT__dcache__DOT____Vcellinp__tagv_ram_way__BRA__0__KET____DOT__u__dina;
        IData/*31:0*/ cpu__DOT__dcache__DOT____VdfgTmp_h3175ceaa__0;
        IData/*31:0*/ __PVT__cpu__DOT__dcache__DOT__data_ram_way__BRA__0__KET____DOT__data_ram_bank__BRA__0__KET____DOT__u__DOT__output_buffer;
        IData/*31:0*/ __PVT__cpu__DOT__dcache__DOT__data_ram_way__BRA__0__KET____DOT__data_ram_bank__BRA__1__KET____DOT__u__DOT__output_buffer;
        IData/*31:0*/ __PVT__cpu__DOT__dcache__DOT__data_ram_way__BRA__0__KET____DOT__data_ram_bank__BRA__2__KET____DOT__u__DOT__output_buffer;
        IData/*31:0*/ __PVT__cpu__DOT__dcache__DOT__data_ram_way__BRA__0__KET____DOT__data_ram_bank__BRA__3__KET____DOT__u__DOT__output_buffer;
        IData/*31:0*/ __PVT__cpu__DOT__dcache__DOT__data_ram_way__BRA__1__KET____DOT__data_ram_bank__BRA__0__KET____DOT__u__DOT__output_buffer;
        IData/*31:0*/ __PVT__cpu__DOT__dcache__DOT__data_ram_way__BRA__1__KET____DOT__data_ram_bank__BRA__1__KET____DOT__u__DOT__output_buffer;
        IData/*31:0*/ __PVT__cpu__DOT__dcache__DOT__data_ram_way__BRA__1__KET____DOT__data_ram_bank__BRA__2__KET____DOT__u__DOT__output_buffer;
        IData/*31:0*/ __PVT__cpu__DOT__dcache__DOT__data_ram_way__BRA__1__KET____DOT__data_ram_bank__BRA__3__KET____DOT__u__DOT__output_buffer;
        IData/*20:0*/ __PVT__cpu__DOT__dcache__DOT__tagv_ram_way__BRA__0__KET____DOT__u__DOT__output_buffer;
        IData/*20:0*/ __PVT__cpu__DOT__dcache__DOT__tagv_ram_way__BRA__1__KET____DOT__u__DOT__output_buffer;
        IData/*31:0*/ __PVT__cpu__DOT__btb__DOT__btb_valid;
        IData/*31:0*/ __PVT__cpu__DOT__btb__DOT__fetch_pc_r;
        IData/*31:0*/ __PVT__cpu__DOT__btb__DOT__btb_match_rd;
        IData/*31:0*/ __PVT__cpu__DOT__btb__DOT__btb_add_entry_dec;
        IData/*31:0*/ __PVT__cpu__DOT__btb__DOT__btb_untaken_entry;
        IData/*31:0*/ __PVT__cpu__DOT__btb__DOT__btb_untaken_entry_r;
        IData/*31:0*/ __PVT__cpu__DOT__btb__DOT__btb_untaken_entry_t;
        IData/*31:0*/ __Vdly__cpu__DOT__u_csr__DOT__csr_crmd;
        IData/*31:0*/ __Vdly__cpu__DOT__u_csr__DOT__csr_tval;
        VlWide<4>/*127:0*/ __Vdly__cpu__DOT__axi_bridge__DOT__write_buffer_data;
        IData/*18:0*/ __Vdlyvval__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_vppn__v0;
        IData/*20:0*/ __Vdlyvval__cpu__DOT__dcache__DOT__tagv_ram_way__BRA__0__KET____DOT__u__DOT__mem_reg__v0;
        IData/*20:0*/ __Vdlyvval__cpu__DOT__dcache__DOT__tagv_ram_way__BRA__1__KET____DOT__u__DOT__mem_reg__v0;
        QData/*63:0*/ __PVT__cpu__DOT__ds_timer_64;
        QData/*63:0*/ __PVT__cpu__DOT__mul_result;
        QData/*63:0*/ __PVT__cpu__DOT__cmt_timer_64;
        QData/*63:0*/ __PVT__cpu__DOT__cycleCnt;
        QData/*63:0*/ __PVT__cpu__DOT__instrCnt;
        QData/*37:0*/ __PVT__cpu__DOT__if_stage__DOT__btb_lock_buffer;
        QData/*63:0*/ __PVT__cpu__DOT__id_stage__DOT__op_31_26_d;
        QData/*32:0*/ __PVT__cpu__DOT__u_div__DOT__UnsignS;
        QData/*32:0*/ __PVT__cpu__DOT__u_div__DOT__UnsignR;
        QData/*32:0*/ __PVT__cpu__DOT__u_div__DOT__tmp_r;
        QData/*32:0*/ __PVT__cpu__DOT__u_div__DOT__tmp_d;
        QData/*32:0*/ __PVT__cpu__DOT__u_div__DOT__result_r;
        QData/*63:0*/ __PVT__cpu__DOT__u_mul__DOT__CalX;
        QData/*32:0*/ __PVT__cpu__DOT__u_mul__DOT__CalY;
        QData/*63:0*/ __PVT__cpu__DOT__u_mul__DOT__SOut;
        QData/*63:0*/ cpu__DOT__u_mul__DOT____Vlvbound_hff1e071f__0;
        QData/*62:0*/ cpu__DOT__u_mul__DOT____VdfgTmp_hb9b19849__0;
        QData/*63:0*/ __PVT__cpu__DOT__u_csr__DOT__timer_64;
        VlUnpacked<IData/*31:0*/, 32> __PVT__cpu__DOT__regs;
        VlUnpacked<IData/*31:0*/, 32> __PVT__cpu__DOT__id_stage__DOT__u_regfile__DOT__rf;
        VlUnpacked<QData/*63:0*/, 17> __PVT__cpu__DOT__u_mul__DOT__BoothRes;
        VlUnpacked<QData/*63:0*/, 17> __PVT__cpu__DOT__u_mul__DOT__SecStageBoothRes;
        VlUnpacked<IData/*18:0*/, 16> __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_vppn;
        VlUnpacked<CData/*0:0*/, 16> __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_e;
        VlUnpacked<SData/*9:0*/, 16> __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_asid;
        VlUnpacked<CData/*0:0*/, 16> __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_g;
    };
    struct {
        VlUnpacked<CData/*5:0*/, 16> __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_ps;
        VlUnpacked<IData/*19:0*/, 16> __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_ppn0;
        VlUnpacked<CData/*1:0*/, 16> __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_plv0;
        VlUnpacked<CData/*1:0*/, 16> __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_mat0;
        VlUnpacked<CData/*0:0*/, 16> __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_d0;
        VlUnpacked<CData/*0:0*/, 16> __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_v0;
        VlUnpacked<IData/*19:0*/, 16> __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_ppn1;
        VlUnpacked<CData/*1:0*/, 16> __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_plv1;
        VlUnpacked<CData/*1:0*/, 16> __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_mat1;
        VlUnpacked<CData/*0:0*/, 16> __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_d1;
        VlUnpacked<CData/*0:0*/, 16> __PVT__cpu__DOT__addr_trans__DOT__tlb_entry__DOT__tlb_v1;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 4>, 2> __PVT__cpu__DOT__icache__DOT__way_bank_addra;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 4>, 2> __PVT__cpu__DOT__icache__DOT__way_bank_dina;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 4>, 2> __PVT__cpu__DOT__icache__DOT__way_bank_douta;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 4>, 2> __PVT__cpu__DOT__icache__DOT__way_bank_ena;
        VlUnpacked<VlUnpacked<CData/*3:0*/, 4>, 2> __PVT__cpu__DOT__icache__DOT__way_bank_wea;
        VlUnpacked<CData/*7:0*/, 2> __PVT__cpu__DOT__icache__DOT__way_tagv_addra;
        VlUnpacked<IData/*20:0*/, 2> __PVT__cpu__DOT__icache__DOT__way_tagv_dina;
        VlUnpacked<IData/*20:0*/, 2> __PVT__cpu__DOT__icache__DOT__way_tagv_douta;
        VlUnpacked<CData/*0:0*/, 2> __PVT__cpu__DOT__icache__DOT__way_tagv_ena;
        VlUnpacked<CData/*0:0*/, 2> __PVT__cpu__DOT__icache__DOT__way_tagv_wea;
        VlUnpacked<IData/*31:0*/, 2> __PVT__cpu__DOT__icache__DOT__way_load_word;
        VlUnpacked<VlWide<4>/*127:0*/, 2> __PVT__cpu__DOT__icache__DOT__way_data;
        VlUnpacked<IData/*31:0*/, 256> __PVT__cpu__DOT__icache__DOT__data_ram_way__BRA__0__KET____DOT__data_ram_bank__BRA__0__KET____DOT__u__DOT__mem_reg;
        VlUnpacked<IData/*31:0*/, 256> __PVT__cpu__DOT__icache__DOT__data_ram_way__BRA__0__KET____DOT__data_ram_bank__BRA__1__KET____DOT__u__DOT__mem_reg;
        VlUnpacked<IData/*31:0*/, 256> __PVT__cpu__DOT__icache__DOT__data_ram_way__BRA__0__KET____DOT__data_ram_bank__BRA__2__KET____DOT__u__DOT__mem_reg;
        VlUnpacked<IData/*31:0*/, 256> __PVT__cpu__DOT__icache__DOT__data_ram_way__BRA__0__KET____DOT__data_ram_bank__BRA__3__KET____DOT__u__DOT__mem_reg;
        VlUnpacked<IData/*31:0*/, 256> __PVT__cpu__DOT__icache__DOT__data_ram_way__BRA__1__KET____DOT__data_ram_bank__BRA__0__KET____DOT__u__DOT__mem_reg;
        VlUnpacked<IData/*31:0*/, 256> __PVT__cpu__DOT__icache__DOT__data_ram_way__BRA__1__KET____DOT__data_ram_bank__BRA__1__KET____DOT__u__DOT__mem_reg;
        VlUnpacked<IData/*31:0*/, 256> __PVT__cpu__DOT__icache__DOT__data_ram_way__BRA__1__KET____DOT__data_ram_bank__BRA__2__KET____DOT__u__DOT__mem_reg;
        VlUnpacked<IData/*31:0*/, 256> __PVT__cpu__DOT__icache__DOT__data_ram_way__BRA__1__KET____DOT__data_ram_bank__BRA__3__KET____DOT__u__DOT__mem_reg;
        VlUnpacked<IData/*20:0*/, 256> __PVT__cpu__DOT__icache__DOT__tagv_ram_way__BRA__0__KET____DOT__u__DOT__mem_reg;
        VlUnpacked<IData/*20:0*/, 256> __PVT__cpu__DOT__icache__DOT__tagv_ram_way__BRA__1__KET____DOT__u__DOT__mem_reg;
        VlUnpacked<CData/*1:0*/, 256> __PVT__cpu__DOT__dcache__DOT__way_d_reg;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 4>, 2> __PVT__cpu__DOT__dcache__DOT__way_bank_addra;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 4>, 2> __PVT__cpu__DOT__dcache__DOT__way_bank_dina;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 4>, 2> __PVT__cpu__DOT__dcache__DOT__way_bank_douta;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 4>, 2> __PVT__cpu__DOT__dcache__DOT__way_bank_ena;
        VlUnpacked<VlUnpacked<CData/*3:0*/, 4>, 2> __PVT__cpu__DOT__dcache__DOT__way_bank_wea;
        VlUnpacked<CData/*7:0*/, 2> __PVT__cpu__DOT__dcache__DOT__way_tagv_addra;
        VlUnpacked<IData/*20:0*/, 2> __PVT__cpu__DOT__dcache__DOT__way_tagv_dina;
        VlUnpacked<IData/*20:0*/, 2> __PVT__cpu__DOT__dcache__DOT__way_tagv_douta;
        VlUnpacked<CData/*0:0*/, 2> __PVT__cpu__DOT__dcache__DOT__way_tagv_ena;
        VlUnpacked<CData/*0:0*/, 2> __PVT__cpu__DOT__dcache__DOT__way_tagv_wea;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 4>, 2> __PVT__cpu__DOT__dcache__DOT__wr_match_way_bank;
        VlUnpacked<IData/*31:0*/, 2> __PVT__cpu__DOT__dcache__DOT__way_load_word;
        VlUnpacked<VlWide<4>/*127:0*/, 2> __PVT__cpu__DOT__dcache__DOT__way_data;
        VlUnpacked<IData/*31:0*/, 256> __PVT__cpu__DOT__dcache__DOT__data_ram_way__BRA__0__KET____DOT__data_ram_bank__BRA__0__KET____DOT__u__DOT__mem_reg;
        VlUnpacked<IData/*31:0*/, 256> __PVT__cpu__DOT__dcache__DOT__data_ram_way__BRA__0__KET____DOT__data_ram_bank__BRA__1__KET____DOT__u__DOT__mem_reg;
        VlUnpacked<IData/*31:0*/, 256> __PVT__cpu__DOT__dcache__DOT__data_ram_way__BRA__0__KET____DOT__data_ram_bank__BRA__2__KET____DOT__u__DOT__mem_reg;
        VlUnpacked<IData/*31:0*/, 256> __PVT__cpu__DOT__dcache__DOT__data_ram_way__BRA__0__KET____DOT__data_ram_bank__BRA__3__KET____DOT__u__DOT__mem_reg;
        VlUnpacked<IData/*31:0*/, 256> __PVT__cpu__DOT__dcache__DOT__data_ram_way__BRA__1__KET____DOT__data_ram_bank__BRA__0__KET____DOT__u__DOT__mem_reg;
        VlUnpacked<IData/*31:0*/, 256> __PVT__cpu__DOT__dcache__DOT__data_ram_way__BRA__1__KET____DOT__data_ram_bank__BRA__1__KET____DOT__u__DOT__mem_reg;
        VlUnpacked<IData/*31:0*/, 256> __PVT__cpu__DOT__dcache__DOT__data_ram_way__BRA__1__KET____DOT__data_ram_bank__BRA__2__KET____DOT__u__DOT__mem_reg;
        VlUnpacked<IData/*31:0*/, 256> __PVT__cpu__DOT__dcache__DOT__data_ram_way__BRA__1__KET____DOT__data_ram_bank__BRA__3__KET____DOT__u__DOT__mem_reg;
        VlUnpacked<IData/*20:0*/, 256> __PVT__cpu__DOT__dcache__DOT__tagv_ram_way__BRA__0__KET____DOT__u__DOT__mem_reg;
        VlUnpacked<IData/*20:0*/, 256> __PVT__cpu__DOT__dcache__DOT__tagv_ram_way__BRA__1__KET____DOT__u__DOT__mem_reg;
        VlUnpacked<IData/*29:0*/, 32> __PVT__cpu__DOT__btb__DOT__btb_pc;
        VlUnpacked<IData/*29:0*/, 32> __PVT__cpu__DOT__btb__DOT__btb_target;
        VlUnpacked<CData/*1:0*/, 32> __PVT__cpu__DOT__btb__DOT__btb_counter;
        VlUnpacked<IData/*29:0*/, 16> __PVT__cpu__DOT__btb__DOT__ras_pc;
        VlUnpacked<IData/*29:0*/, 8> __PVT__cpu__DOT__btb__DOT__ras;
    };

    // INTERNAL VARIABLES
    Vverilator_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vverilator_top_verilator_top(Vverilator_top__Syms* symsp, const char* v__name);
    ~Vverilator_top_verilator_top();
    VL_UNCOPYABLE(Vverilator_top_verilator_top);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
