// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vverilator_top.h for the primary calling header

#include "verilated.h"
#include "verilated_dpi.h"

#include "Vverilator_top__Syms.h"
#include "Vverilator_top___024root.h"

#ifdef VL_DEBUG
VL_ATTR_COLD void Vverilator_top___024root___dump_triggers__ico(Vverilator_top___024root* vlSelf);
#endif  // VL_DEBUG

void Vverilator_top___024root___eval_triggers__ico(Vverilator_top___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vverilator_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vverilator_top___024root___eval_triggers__ico\n"); );
    // Body
    vlSelf->__VicoTriggered.at(0U) = (0U == vlSelf->__VicoIterCount);
#ifdef VL_DEBUG
    if (VL_UNLIKELY(vlSymsp->_vm_contextp__->debug())) {
        Vverilator_top___024root___dump_triggers__ico(vlSelf);
    }
#endif
}

void Vverilator_top_verilator_top___ico_sequent__TOP__verilator_top__0(Vverilator_top_verilator_top* vlSelf);

void Vverilator_top___024root___eval_ico(Vverilator_top___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vverilator_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vverilator_top___024root___eval_ico\n"); );
    // Body
    if (vlSelf->__VicoTriggered.at(0U)) {
        Vverilator_top_verilator_top___ico_sequent__TOP__verilator_top__0((&vlSymsp->TOP__verilator_top));
        vlSelf->__Vm_traceActivity[1U] = 1U;
    }
}

#ifdef VL_DEBUG
VL_ATTR_COLD void Vverilator_top___024root___dump_triggers__act(Vverilator_top___024root* vlSelf);
#endif  // VL_DEBUG

void Vverilator_top___024root___eval_triggers__act(Vverilator_top___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vverilator_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vverilator_top___024root___eval_triggers__act\n"); );
    // Body
    vlSelf->__VactTriggered.at(0U) = ((IData)(vlSelf->clk) 
                                      & (~ (IData)(vlSelf->__Vtrigrprev__TOP__clk)));
    vlSelf->__VactTriggered.at(1U) = (((IData)(vlSelf->clk) 
                                       & (~ (IData)(vlSelf->__Vtrigrprev__TOP__clk))) 
                                      | ((IData)(vlSelf->rst) 
                                         & (~ (IData)(vlSelf->__Vtrigrprev__TOP__rst))));
    vlSelf->__Vtrigrprev__TOP__clk = vlSelf->clk;
    vlSelf->__Vtrigrprev__TOP__rst = vlSelf->rst;
#ifdef VL_DEBUG
    if (VL_UNLIKELY(vlSymsp->_vm_contextp__->debug())) {
        Vverilator_top___024root___dump_triggers__act(vlSelf);
    }
#endif
}

void Vverilator_top_verilator_top___nba_sequent__TOP__verilator_top__0(Vverilator_top_verilator_top* vlSelf);
void Vverilator_top_verilator_top___nba_sequent__TOP__verilator_top__1(Vverilator_top_verilator_top* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__firs__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__63__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__62__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__61__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__60__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__59__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__58__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__57__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__56__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__55__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__54__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__53__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__52__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__51__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__50__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__49__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__48__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__47__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__46__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__45__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__44__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__43__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__42__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__41__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__40__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__39__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__38__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__37__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__36__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__35__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__34__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__33__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__32__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__31__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__30__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__29__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__28__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__27__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__26__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__25__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__24__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__23__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__22__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__21__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__20__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__19__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__18__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__17__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__16__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__15__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__14__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__13__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__12__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__11__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__10__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__9__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__8__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__7__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__6__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__5__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__4__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__3__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__2__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__1__KET____DOT__bi__0(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__2__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__3__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__4__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__5__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__6__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__7__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__8__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__9__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__10__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__11__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__12__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__13__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__14__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__15__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__16__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__17__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__18__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__19__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__20__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__21__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__22__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__23__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__24__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__25__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__26__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__27__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__28__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__29__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__30__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__31__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__32__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__33__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__34__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__35__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__36__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__37__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__38__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__39__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__40__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__41__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__42__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__43__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__44__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__45__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__46__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__47__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__48__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__49__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__50__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__51__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__52__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__53__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__54__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__55__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__56__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__57__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__58__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__59__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__60__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__61__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__62__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_verilator_top___nba_sequent__TOP__verilator_top__2(Vverilator_top_verilator_top* vlSelf);
void Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__63__KET____DOT__bi__1(Vverilator_top_WallaceTreeBase* vlSelf);
void Vverilator_top_verilator_top___nba_sequent__TOP__verilator_top__3(Vverilator_top_verilator_top* vlSelf);
void Vverilator_top_verilator_top___nba_sequent__TOP__verilator_top__4(Vverilator_top_verilator_top* vlSelf);
void Vverilator_top_verilator_top___nba_sequent__TOP__verilator_top__5(Vverilator_top_verilator_top* vlSelf);
void Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__fir__0(Vverilator_top_BoothInterBase* vlSelf);
void Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__2__KET____DOT__ai__0(Vverilator_top_BoothInterBase* vlSelf);
void Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__4__KET____DOT__ai__0(Vverilator_top_BoothInterBase* vlSelf);
void Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__6__KET____DOT__ai__0(Vverilator_top_BoothInterBase* vlSelf);
void Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__8__KET____DOT__ai__0(Vverilator_top_BoothInterBase* vlSelf);
void Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__10__KET____DOT__ai__0(Vverilator_top_BoothInterBase* vlSelf);
void Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__12__KET____DOT__ai__0(Vverilator_top_BoothInterBase* vlSelf);
void Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__14__KET____DOT__ai__0(Vverilator_top_BoothInterBase* vlSelf);
void Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__16__KET____DOT__ai__0(Vverilator_top_BoothInterBase* vlSelf);
void Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__18__KET____DOT__ai__0(Vverilator_top_BoothInterBase* vlSelf);
void Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__20__KET____DOT__ai__0(Vverilator_top_BoothInterBase* vlSelf);
void Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__22__KET____DOT__ai__0(Vverilator_top_BoothInterBase* vlSelf);
void Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__24__KET____DOT__ai__0(Vverilator_top_BoothInterBase* vlSelf);
void Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__26__KET____DOT__ai__0(Vverilator_top_BoothInterBase* vlSelf);
void Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__28__KET____DOT__ai__0(Vverilator_top_BoothInterBase* vlSelf);
void Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__30__KET____DOT__ai__0(Vverilator_top_BoothInterBase* vlSelf);
void Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__las__0(Vverilator_top_BoothInterBase* vlSelf);
void Vverilator_top_verilator_top___nba_sequent__TOP__verilator_top__6(Vverilator_top_verilator_top* vlSelf);
void Vverilator_top_verilator_top___nba_sequent__TOP__verilator_top__7(Vverilator_top_verilator_top* vlSelf);
void Vverilator_top_verilator_top___nba_comb__TOP__verilator_top__0(Vverilator_top_verilator_top* vlSelf);

void Vverilator_top___024root___eval_nba(Vverilator_top___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vverilator_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vverilator_top___024root___eval_nba\n"); );
    // Body
    if (vlSelf->__VnbaTriggered.at(0U)) {
        Vverilator_top_verilator_top___nba_sequent__TOP__verilator_top__0((&vlSymsp->TOP__verilator_top));
        vlSelf->__Vm_traceActivity[2U] = 1U;
        Vverilator_top_verilator_top___nba_sequent__TOP__verilator_top__1((&vlSymsp->TOP__verilator_top));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__firs__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__firs));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__63__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__63__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__62__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__62__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__61__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__61__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__60__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__60__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__59__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__59__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__58__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__58__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__57__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__57__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__56__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__56__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__55__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__55__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__54__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__54__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__53__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__53__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__52__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__52__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__51__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__51__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__50__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__50__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__49__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__49__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__48__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__48__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__47__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__47__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__46__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__46__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__45__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__45__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__44__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__44__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__43__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__43__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__42__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__42__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__41__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__41__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__40__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__40__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__39__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__39__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__38__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__38__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__37__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__37__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__36__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__36__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__35__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__35__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__34__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__34__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__33__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__33__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__32__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__32__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__31__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__31__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__30__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__30__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__29__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__29__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__28__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__28__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__27__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__27__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__26__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__26__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__25__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__25__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__24__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__24__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__23__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__23__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__22__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__22__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__21__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__21__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__20__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__20__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__19__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__19__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__18__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__18__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__17__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__17__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__16__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__16__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__15__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__15__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__14__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__14__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__13__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__13__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__12__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__12__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__11__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__11__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__10__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__10__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__9__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__9__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__8__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__8__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__7__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__7__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__6__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__6__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__5__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__5__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__4__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__4__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__3__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__3__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__2__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__2__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__1__KET____DOT__bi__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__1__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__2__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__2__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__3__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__3__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__4__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__4__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__5__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__5__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__6__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__6__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__7__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__7__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__8__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__8__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__9__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__9__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__10__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__10__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__11__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__11__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__12__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__12__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__13__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__13__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__14__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__14__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__15__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__15__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__16__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__16__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__17__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__17__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__18__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__18__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__19__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__19__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__20__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__20__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__21__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__21__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__22__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__22__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__23__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__23__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__24__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__24__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__25__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__25__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__26__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__26__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__27__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__27__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__28__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__28__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__29__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__29__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__30__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__30__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__31__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__31__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__32__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__32__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__33__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__33__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__34__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__34__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__35__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__35__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__36__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__36__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__37__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__37__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__38__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__38__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__39__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__39__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__40__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__40__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__41__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__41__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__42__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__42__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__43__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__43__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__44__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__44__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__45__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__45__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__46__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__46__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__47__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__47__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__48__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__48__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__49__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__49__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__50__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__50__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__51__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__51__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__52__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__52__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__53__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__53__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__54__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__54__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__55__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__55__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__56__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__56__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__57__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__57__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__58__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__58__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__59__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__59__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__60__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__60__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__61__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__61__KET____DOT__bi));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__62__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__62__KET____DOT__bi));
        Vverilator_top_verilator_top___nba_sequent__TOP__verilator_top__2((&vlSymsp->TOP__verilator_top));
        Vverilator_top_WallaceTreeBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__63__KET____DOT__bi__1((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__63__KET____DOT__bi));
        Vverilator_top_verilator_top___nba_sequent__TOP__verilator_top__3((&vlSymsp->TOP__verilator_top));
    }
    if (vlSelf->__VnbaTriggered.at(1U)) {
        Vverilator_top_verilator_top___nba_sequent__TOP__verilator_top__4((&vlSymsp->TOP__verilator_top));
        vlSelf->__Vm_traceActivity[3U] = 1U;
    }
    if (vlSelf->__VnbaTriggered.at(0U)) {
        Vverilator_top_verilator_top___nba_sequent__TOP__verilator_top__5((&vlSymsp->TOP__verilator_top));
        vlSelf->__Vm_traceActivity[4U] = 1U;
        Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__fir__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__fir));
        Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__2__KET____DOT__ai__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__2__KET____DOT__ai));
        Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__4__KET____DOT__ai__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__4__KET____DOT__ai));
        Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__6__KET____DOT__ai__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__6__KET____DOT__ai));
        Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__8__KET____DOT__ai__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__8__KET____DOT__ai));
        Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__10__KET____DOT__ai__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__10__KET____DOT__ai));
        Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__12__KET____DOT__ai__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__12__KET____DOT__ai));
        Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__14__KET____DOT__ai__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__14__KET____DOT__ai));
        Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__16__KET____DOT__ai__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__16__KET____DOT__ai));
        Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__18__KET____DOT__ai__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__18__KET____DOT__ai));
        Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__20__KET____DOT__ai__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__20__KET____DOT__ai));
        Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__22__KET____DOT__ai__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__22__KET____DOT__ai));
        Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__24__KET____DOT__ai__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__24__KET____DOT__ai));
        Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__26__KET____DOT__ai__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__26__KET____DOT__ai));
        Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__28__KET____DOT__ai__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__28__KET____DOT__ai));
        Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__30__KET____DOT__ai__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__30__KET____DOT__ai));
        Vverilator_top_BoothInterBase___nba_sequent__TOP__verilator_top__cpu__DOT__u_mul__DOT__las__0((&vlSymsp->TOP__verilator_top__cpu__DOT__u_mul__DOT__las));
        Vverilator_top_verilator_top___nba_sequent__TOP__verilator_top__6((&vlSymsp->TOP__verilator_top));
    }
    if (vlSelf->__VnbaTriggered.at(1U)) {
        Vverilator_top_verilator_top___nba_sequent__TOP__verilator_top__7((&vlSymsp->TOP__verilator_top));
        vlSelf->__Vm_traceActivity[5U] = 1U;
    }
    if ((vlSelf->__VnbaTriggered.at(0U) | vlSelf->__VnbaTriggered.at(1U))) {
        Vverilator_top_verilator_top___nba_comb__TOP__verilator_top__0((&vlSymsp->TOP__verilator_top));
        vlSelf->__Vm_traceActivity[6U] = 1U;
    }
}
