// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef VERILATED_VVERILATOR_TOP__SYMS_H_
#define VERILATED_VVERILATOR_TOP__SYMS_H_  // guard

#include "verilated.h"

// INCLUDE MODEL CLASS

#include "Vverilator_top.h"

// INCLUDE MODULE CLASSES
#include "Vverilator_top___024root.h"
#include "Vverilator_top_verilator_top.h"
#include "Vverilator_top_BoothInterBase.h"
#include "Vverilator_top_WallaceTreeBase.h"

// DPI TYPES for DPI Export callbacks (Internal use)

// SYMS CLASS (contains all model state)
class Vverilator_top__Syms final : public VerilatedSyms {
  public:
    // INTERNAL STATE
    Vverilator_top* const __Vm_modelp;
    bool __Vm_activity = false;  ///< Used by trace routines to determine change occurred
    uint32_t __Vm_baseCode = 0;  ///< Used by trace routines when tracing multiple models
    VlDeleter __Vm_deleter;
    bool __Vm_didInit = false;

    // MODULE INSTANCE STATE
    Vverilator_top___024root       TOP;
    Vverilator_top_verilator_top   TOP__verilator_top;
    Vverilator_top_BoothInterBase  TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__10__KET____DOT__ai;
    Vverilator_top_BoothInterBase  TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__12__KET____DOT__ai;
    Vverilator_top_BoothInterBase  TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__14__KET____DOT__ai;
    Vverilator_top_BoothInterBase  TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__16__KET____DOT__ai;
    Vverilator_top_BoothInterBase  TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__18__KET____DOT__ai;
    Vverilator_top_BoothInterBase  TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__20__KET____DOT__ai;
    Vverilator_top_BoothInterBase  TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__22__KET____DOT__ai;
    Vverilator_top_BoothInterBase  TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__24__KET____DOT__ai;
    Vverilator_top_BoothInterBase  TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__26__KET____DOT__ai;
    Vverilator_top_BoothInterBase  TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__28__KET____DOT__ai;
    Vverilator_top_BoothInterBase  TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__2__KET____DOT__ai;
    Vverilator_top_BoothInterBase  TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__30__KET____DOT__ai;
    Vverilator_top_BoothInterBase  TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__4__KET____DOT__ai;
    Vverilator_top_BoothInterBase  TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__6__KET____DOT__ai;
    Vverilator_top_BoothInterBase  TOP__verilator_top__cpu__DOT__u_mul__DOT__boothfor__BRA__8__KET____DOT__ai;
    Vverilator_top_BoothInterBase  TOP__verilator_top__cpu__DOT__u_mul__DOT__fir;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__firs;
    Vverilator_top_BoothInterBase  TOP__verilator_top__cpu__DOT__u_mul__DOT__las;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__10__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__11__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__12__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__13__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__14__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__15__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__16__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__17__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__18__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__19__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__1__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__20__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__21__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__22__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__23__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__24__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__25__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__26__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__27__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__28__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__29__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__2__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__30__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__31__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__32__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__33__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__34__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__35__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__36__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__37__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__38__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__39__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__3__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__40__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__41__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__42__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__43__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__44__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__45__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__46__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__47__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__48__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__49__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__4__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__50__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__51__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__52__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__53__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__54__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__55__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__56__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__57__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__58__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__59__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__5__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__60__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__61__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__62__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__63__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__6__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__7__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__8__KET____DOT__bi;
    Vverilator_top_WallaceTreeBase TOP__verilator_top__cpu__DOT__u_mul__DOT__wallacefor__BRA__9__KET____DOT__bi;

    // SCOPE NAMES
    VerilatedScope __Vscope_verilator_top;

    // CONSTRUCTORS
    Vverilator_top__Syms(VerilatedContext* contextp, const char* namep, Vverilator_top* modelp);
    ~Vverilator_top__Syms();

    // METHODS
    const char* name() { return TOP.name(); }
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

#endif  // guard
