################################################################################
# LA CPU timing analysis script
#
# Target: xc7a200tfbg676-1 (default, configurable)
# Mode:   Out-of-Context synthesis + implementation
#
# Usage:
#   vivado -mode batch -source scripts/synth_timing.tcl
#   vivado -mode batch -source scripts/synth_timing.tcl -tclargs -freq 150
#
# Outputs (in ./vivado_timing/):
#   timing_summary.rpt   post-route timing summary
#   utilization.rpt      resource utilization
#   critical_path.rpt    worst setup paths
#   timing_summary.txt   human-readable frequency estimate
################################################################################

#==============================================================================
# Configuration
#==============================================================================

set script_dir  [file dirname [info script]]
set repo_root   [file normalize "$script_dir/.."]
set rtl_dir     [file normalize "$repo_root/mycpu_env/myCPU/v_src"]
set project_dir [file normalize "$repo_root/vivado_timing"]
set output_dir  $project_dir

set fpga_part    "xc7a200tfbg676-1"
set project_name "la_cpu_timing"
set top_module   "core_top"
set num_jobs     8

# Target clock frequency in MHz (used for constraint, not hard limit)
set target_freq_mhz 100.0
set target_period_ns [expr {1000.0 / $target_freq_mhz}]

# Parse command line args
if {[info exists argc]} {
    for {set i 0} {$i < $argc} {incr i} {
        set arg [lindex $argv $i]
        switch -exact -- $arg {
            "-freq" {
                incr i
                set target_freq_mhz [lindex $argv $i]
                set target_period_ns [expr {1000.0 / double($target_freq_mhz)}]
            }
            "-jobs" {
                incr i
                set num_jobs [lindex $argv $i]
            }
            "-part" {
                incr i
                set fpga_part [lindex $argv $i]
            }
            "-top" {
                incr i
                set top_module [lindex $argv $i]
            }
            default {
                # Ignore unknown args for forward compatibility
            }
        }
    }
}

puts "=============================================="
puts " LA CPU Timing Analysis"
puts "=============================================="
puts " FPGA Part   : $fpga_part"
puts " Top Module  : $top_module"
puts " Target Freq : ${target_freq_mhz} MHz (period = [format %.3f $target_period_ns] ns)"
puts " RTL Dir     : $rtl_dir"
puts " Output Dir  : $output_dir"
puts "=============================================="

#==============================================================================
# Discover source files
#==============================================================================

set all_rtl_sources [lsort [glob -nocomplain "$rtl_dir/*.v"]]
set rtl_sources [list]

foreach src $all_rtl_sources {
    set name [file tail $src]
    # Simulation-only wrapper; exclude from synthesis flow.
    if {$name eq "verilator_top.v"} {
        continue
    }
    lappend rtl_sources $src
}

if {[llength $rtl_sources] == 0} {
    puts "ERROR: no RTL source files found under $rtl_dir"
    exit 1
}

#==============================================================================
# Create project
#==============================================================================

file mkdir $output_dir
create_project $project_name $project_dir -part $fpga_part -force
set_property target_language Verilog [current_project]

#==============================================================================
# Add source files
#==============================================================================

puts "Adding RTL sources..."
foreach src $rtl_sources {
    add_files -norecurse $src
    puts "  + [file tail $src]"
}

set_property include_dirs [list $rtl_dir] [current_fileset]
set_property top $top_module [current_fileset]

#==============================================================================
# Constraints
#==============================================================================

set base_xdc [file normalize "$script_dir/cpu_timing.xdc"]
if {![file exists $base_xdc]} {
    puts "ERROR: baseline XDC not found: $base_xdc"
    exit 1
}
add_files -fileset constrs_1 -norecurse $base_xdc
puts "  + Constraints: [file tail $base_xdc]"

# Override XDC with target frequency and I/O false-path for OOC Fmax evaluation.
set override_xdc "$project_dir/override_clk.xdc"
set fh [open $override_xdc w]
puts $fh "# Auto-generated by scripts/synth_timing.tcl"
puts $fh [format {create_clock -period %.3f -name cpu_clk [get_ports aclk]} $target_period_ns]
puts $fh {set_false_path -from [get_ports aresetn]}
close $fh
add_files -fileset constrs_1 -norecurse $override_xdc
set_property IS_ENABLED false [get_files $base_xdc]
puts "  + Override clock: ${target_freq_mhz} MHz ([format %.3f $target_period_ns] ns)"

#==============================================================================
# Synthesis / implementation strategies
#==============================================================================

set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
set_property STEPS.SYNTH_DESIGN.ARGS.FLATTEN_HIERARCHY rebuilt [get_runs synth_1]
catch {set_property STEPS.SYNTH_DESIGN.ARGS.GLOBAL_RETIMING true [get_runs synth_1]}
set_property STEPS.SYNTH_DESIGN.ARGS.DIRECTIVE PerformanceOptimized [get_runs synth_1]

set_property strategy "Performance_ExplorePostRoutePhysOpt" [get_runs impl_1]
set_property STEPS.PHYS_OPT_DESIGN.IS_ENABLED true [get_runs impl_1]
set_property STEPS.POST_ROUTE_PHYS_OPT_DESIGN.IS_ENABLED true [get_runs impl_1]

#==============================================================================
# Run synthesis
#==============================================================================

puts ""
puts "=============================================="
puts " Step 1/3: Synthesis"
puts "=============================================="

reset_run synth_1
reset_run impl_1
launch_runs synth_1 -jobs $num_jobs
wait_on_run synth_1

set synth_status [get_property STATUS [get_runs synth_1]]
puts "Synthesis status: $synth_status"
if {[get_property PROGRESS [get_runs synth_1]] != "100%"} {
    puts "ERROR: synthesis failed"
    exit 1
}

#==============================================================================
# Run implementation
#==============================================================================

puts ""
puts "=============================================="
puts " Step 2/3: Implementation"
puts "=============================================="

launch_runs impl_1 -jobs $num_jobs
wait_on_run impl_1

set impl_status [get_property STATUS [get_runs impl_1]]
puts "Implementation status: $impl_status"
if {[get_property PROGRESS [get_runs impl_1]] != "100%"} {
    puts "WARNING: implementation may not be fully routed"
}

#==============================================================================
# Reports and Fmax estimation
#==============================================================================

puts ""
puts "=============================================="
puts " Step 3/3: Timing Reports"
puts "=============================================="

open_run impl_1

set timing_rpt "$output_dir/timing_summary.rpt"
report_timing_summary \
    -delay_type min_max \
    -max_paths 20 \
    -input_pins \
    -routable_nets \
    -file $timing_rpt

set util_rpt "$output_dir/utilization.rpt"
report_utilization -hierarchical -hierarchical_depth 3 -file $util_rpt

set crit_rpt "$output_dir/critical_path.rpt"
report_timing \
    -max_paths 10 \
    -nworst 1 \
    -delay_type max \
    -sort_by slack \
    -input_pins \
    -file $crit_rpt

set clk_rpt "$output_dir/clock_interaction.rpt"
report_clock_interaction -file $clk_rpt

# Query WNS directly from timing DB.
set wns 0.0
set timing_path [get_timing_paths -max_paths 1 -delay_type max -sort_by slack]
if {[llength $timing_path] > 0} {
    set wns [get_property SLACK [lindex $timing_path 0]]
}

set achievable_period_ns [expr {$target_period_ns - $wns}]
if {$achievable_period_ns <= 0.0} {
    set achievable_period_ns 0.001
}
set achievable_freq_mhz [expr {1000.0 / $achievable_period_ns}]

set summary_file "$output_dir/timing_summary.txt"
set sf [open $summary_file w]
puts $sf "========================================================"
puts $sf "  LA CPU Timing Analysis Result"
puts $sf "========================================================"
puts $sf ""
puts $sf "  Device               : $fpga_part"
puts $sf "  Top                  : $top_module"
puts $sf "  Target frequency     : [format %.1f $target_freq_mhz] MHz"
puts $sf "  Target period        : [format %.3f $target_period_ns] ns"
puts $sf "  WNS                  : [format %.3f $wns] ns"
puts $sf "  Estimated period     : [format %.3f $achievable_period_ns] ns"
puts $sf "  Estimated frequency  : [format %.1f $achievable_freq_mhz] MHz"
puts $sf "  FMAX_MHZ=[format %.1f $achievable_freq_mhz]"
puts $sf ""
if {$wns >= 0} {
    puts $sf "  STATUS: TIMING MET at target frequency"
} else {
    puts $sf "  STATUS: TIMING VIOLATED at target frequency"
}
puts $sf "========================================================"
close $sf

puts ""
puts "=============================================="
puts " TIMING RESULT"
puts "=============================================="
puts "  Target      : [format %.1f $target_freq_mhz] MHz ([format %.3f $target_period_ns] ns)"
puts "  WNS         : [format %.3f $wns] ns"
puts "  Est. Fmax   : [format %.1f $achievable_freq_mhz] MHz"
if {$wns >= 0} {
    puts "  Status      : TIMING MET"
} else {
    puts "  Status      : TIMING VIOLATED"
}
puts "  Summary     : $summary_file"
puts "=============================================="
puts ""
puts "Reports generated in: $output_dir"

exit 0
